### ISSUE TITLE
Failed to spawn: unexpectedly timed out while waiting for app to launch

### ISSUE THREAD

**Issue by miller93** [frida/frida-core#102]
Updated frida to latest 9.0.8 and i'm still having the same issue whenever I try to spawn any app in jailbroken IOS 7.1.2 using `frida-trace -U -f com.facebook.Facebook` the app opens in the device however, I still get `Failed to spawn: unexpectedly timed out while waiting for app to launch` not sure why... everything else works just fine. I've tried multiple apps but they all have the same problem

**Comment by ddaddy** [comment]
I have a similar issue that happens in both `9.0.8` & `9.0.13`.
When I try to spawn an app, the whole UI on the iOS device freezes, and only killing SpringBoard brings it back to life.
Whilst in the console it waits then eventually shows the message `Failed to spawn: unable to launch iOS app: timeout `

Rolling back to `8.2.1` works fine.

**Comment by ddaddy** [comment]
Doing a bit more testing, going back to `8.2.2` works fine, however as soon as I go up to `8.2.4` or above, I get `Failed to spawn: unable to connect to remote frida-server: Unable to connect (connection refused)` error.

**Comment by rustymagnet3000** [comment]
I hit the same `Failed to spawn: timed out while waiting for session to establish ` on Frida version `9.1.1.`

**Comment by oleavr** [comment]
Not able to reproduce this. Contributions welcome!

**Comment by zhangkn** [comment]
frida -U -f com.apple.mobilemail 

Console的信息
```
Dec 15 19:07:50 A01-27 SpringBoard[627] <Warning>: BSXPCMessage received error for message: Connection interrupted
Dec 15 19:07:50 A01-27 SpringBoard[627] <Warning>: [snapshot] <com.apple.mobilemail> unable to snapshot because snapshot data provider could not be created for scene: com.apple.mobilemail
Dec 15 19:07:50 A01-27 SpringBoard[627] <Warning>: Application 'UIKitApplication:com.apple.mobilemail[0x1676]' exited voluntarily.
Dec 15 19:09:40 A01-27 UserEventAgent[41] <Error>: watchdog: com.apple.backboardd not responding; forcing a crash
Dec 15 19:09:40 A01-27 UserEventAgent[41] <Notice>: watchdog: can be disabled with the shell command: defaults write com.apple.mobilewatchdog WatchdogEnabled -bool no
Dec 15 19:09:40 A01-27 ReportCrash[677] <Notice>: MS:Notice: Injecting: (null) [ReportCrash] (1141.16)
Dec 15 19:09:40 A01-27 ReportCrash[677] <Notice>: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/RocketBootstrap.dylib
Dec 15 19:09:40 A01-27 ReportCrash[677] <Error>: task_set_exception_ports(B07, 400, F03, 0, 0) failed with error (4: (os/kern) invalid argument)
Dec 15 19:09:40 A01-27 ReportCrash[677] <Notice>: Saved report to /Library/Logs/CrashReporter/stacks+backboardd-2017-12-15-190940.ips
```

**Comment by mustafairan** [comment]
I have the same issue on frida 14.2.18 over IOS 12.2
Eventhough brida is able to spawn the app, it shows me the error below:

`Pyro server shutted down  Pyro server started correctly  Exception with spawn application net.razorvine.pyro.PyroException: [frida.TimedOutError] unexpectedly timed out while waiting for app to launch net.razorvine.pyro.serializer.PyroExceptionSerpent.FromSerpentDict(PyroExceptionSerpent.java:32) net.razorvine.pyro.serializer.SerpentSerializer$DictConverter.convert(SerpentSerializer.java:58) net.razorvine.serpent.ObjectifyVisitor.visit(ObjectifyVisitor.java:69) net.razorvine.serpent.ast.DictNode.accept(DictNode.java:8) net.razorvine.serpent.ast.Ast.accept(Ast.java:51) net.razorvine.serpent.ast.Ast.getData(Ast.java:45) net.razorvine.pyro.serializer.SerpentSerializer.deserializeData(SerpentSerializer.java:47) net.razorvine.pyro.PyroProxy.internal_call(PyroProxy.java:272) net.razorvine.pyro.PyroProxy.call(PyroProxy.java:178) burp.BurpExtender.actionPerformed(BurpExtender.java:1224) java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) java.desktop/java.awt.Component.processMouseEvent(Component.java:6614) java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342) java.desktop/java.awt.Component.processEvent(Component.java:6379) java.desktop/java.awt.Container.processEvent(Container.java:2263) java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990) java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321) java.desktop/java.awt.Component.dispatchEvent(Component.java:4822) java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919) java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548) java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489) java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307) java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769) java.desktop/java.awt.Component.dispatchEvent(Component.java:4822) java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) java.base/java.security.AccessController.doPrivileged(AccessController.java:391) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745) java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743) java.base/java.security.AccessController.doPrivileged(AccessController.java:391) java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)  `
