### ISSUE TITLE
Failed to attach: unable to connect to remote frida-server: Unable to connect (connection refused)

### ISSUE THREAD

**Issue by ddaddy** [frida/frida-core#103]
I just upgraded to frida 9.0.9 and now I just get the error:
`Failed to attach: unable to connect to remote frida-server: Unable to connect (connection refused)`

This is on iOS 8.4 and worked fine with Frida 8.2.1

**Comment by ddaddy** [comment]
A bit more info, it seems maybe you have removed 32bit support?

```(re.frida.server[803]) <Error>: Program specified by service does not contain one of the requested architectures:```

**Comment by oleavr** [comment]
The package has been split into two – please install the “Frida for 32-bit devices” package.

**Comment by ddaddy** [comment]
Thanks. I missed that as Cydia simply updated the old package.
