### ISSUE TITLE
Process.platform accuracy

### ISSUE THREAD

**Issue by nezetic** [frida/frida-core#104]
As I use Frida more and more (amazing job btw ;) ), on multiple platforms and architectures, I'm a bit frustrated by how Process.platform work.

As far I understand, it only return GUM_SCRIPT_PLATFORM, so basically linux, darwin, etc.

And I didn't found any reliable way to know if a remote frida-server is running on iOS or Android.

For iOS, you can do something like "darwin on ARM".
But Android, you can't do "linux on ARM", because it can be both android or linux server.

I see two solutions : 
- A more accurate Process.platform, adding android, macos, ios.
- A Frida object providing more data about server than version, like architecture, target build, etc.

I like the 2nd option better because it will not break user scripts, but it can be confusing if Process.platform say "I'm a darwin process" and Frida.platform say "I'm an iOS server".

**Comment by oleavr** [comment]
Very good point, thanks! I think something similar to the second option is the best. Perhaps something like `Process.os = { name: 'ios', version: '10.1' }'`?

**Comment by nezetic** [comment]
What I really enjoy about Frida is writing (sometime complex) scripts once, and see them working everywhere.

The more we can grab about remote OS, the better. Versioning is interesting as it would allow scripts to adapt to system API modifications. Today, without accurate OS name, it's not even possible to decide which flags to pass to let's say _dlopen_ (as values are different between darwin, linux and android...).

But I know from experience that even simple things like OS "version" is a pain to define / have on multi-platform projects.

**Comment by oleavr** [comment]
Sounds good. And yeah I totally agree, that's also been my experience, so we'll need to find some middle-ground that's good enough without going all the way to specifying Linux distro version etc.

Let's keep tracking this at frida/frida-gum#192.
