### ISSUE TITLE
/usr/bin/ld:.libs/libfrida-gadget-1.0.ver:2: syntax error in VERSION script

### ISSUE THREAD

**Issue by hackappcom** [frida/frida-core#11]
Hi, while making frida-core:

[afx237@bright ~/frida/frida-core frida-linux-x86_64]
$ make
make  all-recursive
make[1]: Entering directory '/home/afx237/frida/frida-core'
Making all in tools
make[2]: Entering directory '/home/afx237/frida/frida-core/tools'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/afx237/frida/frida-core/tools'
Making all in lib
make[2]: Entering directory '/home/afx237/frida/frida-core/lib'
Making all in interfaces
make[3]: Entering directory '/home/afx237/frida/frida-core/lib/interfaces'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/afx237/frida/frida-core/lib/interfaces'
Making all in pipe
make[3]: Entering directory '/home/afx237/frida/frida-core/lib/pipe'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/afx237/frida/frida-core/lib/pipe'
Making all in agent
make[3]: Entering directory '/home/afx237/frida/frida-core/lib/agent'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/afx237/frida/frida-core/lib/agent'
make[3]: Entering directory '/home/afx237/frida/frida-core/lib'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/afx237/frida/frida-core/lib'
make[2]: Leaving directory '/home/afx237/frida/frida-core/lib'
Making all in src
make[2]: Entering directory '/home/afx237/frida/frida-core/src'
make  all-am
make[3]: Entering directory '/home/afx237/frida/frida-core/src'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/afx237/frida/frida-core/src'
make[2]: Leaving directory '/home/afx237/frida/frida-core/src'
Making all in server
make[2]: Entering directory '/home/afx237/frida/frida-core/server'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/afx237/frida/frida-core/server'
Making all in gadget
make[2]: Entering directory '/home/afx237/frida/frida-core/gadget'
  CCLD     libfrida-gadget-1.0.la

*** Warning: Linking the shared library libfrida-gadget-1.0.la against the
*** static library ../lib/agent/.libs/libfrida-agent.a is not portable!
/usr/bin/ld:.libs/libfrida-gadget-1.0.ver:2: syntax error in VERSION script
collect2: error: ld returned 1 exit status
Makefile:490: recipe for target 'libfrida-gadget-1.0.la' failed
make[2]: *** [libfrida-gadget-1.0.la] Error 1
make[2]: Leaving directory '/home/afx237/frida/frida-core/gadget'
Makefile:489: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/afx237/frida/frida-core'
Makefile:397: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by oleavr** [comment]
Hey,

I'm terrible sorry this one slipped through the cracks! Are you still seeing this issue? What does your build environment look like?

Thanks!

**Comment by oleavr** [comment]
This should now be fixed. Thanks for reporting!
