### ISSUE TITLE
iOS Retrieving Crypto Args

### ISSUE THREAD

**Issue by JohnWickJM** [frida/frida-core#110]
Quick question, 
So if you have the following:
@interface SecKeyWrapper : NSObject
{
    NSData *publicTag;
    ...........
}
- (id)doCipher:(id)arg1 key:(id)arg2 context:(unsigned int)arg3 padding:(unsigned int *)arg4;

Shouldn't you be able to do:
```

var sendCipher = ObjC.classes.SecKeyWrapper["- doCipher:"];

if(ObjC.available){
	for(var className in ObjC.classes) {  
	    if (ObjC.classes.hasOwnProperty(className)) {
	        if(className == "SecKeyWrapper") {
	            send("Found class : " + className);

	            Interceptor.attach(sendCipher.implementation, {
				  onEnter: function(args) {
				    // args[0] is self
				    // args[1] is selector (SEL "doCipher:")
				    // args[2] holds the first function argument
				    var message = ObjC.Object(args[2]);
				    console.log("\n[SecKeyWrapper doCipher:@\""
				        + message.toString() + "\"]");
				  }
		  });
	        }
	    }
	}
}
```
No?

**Comment by oleavr** [comment]
That loops isn't necessary for finding a specific class. To get hold of the `Foo` class, just access it directly through `ObjC.classes.Foo`. You can then `!== undefined` in case you need to check if this specific app has that class or not.

Regarding `doCipher`, its method name isn't just `- doCipher:`, it is: `- doCipher:key:context:padding:`. If in doubt, you can `console.log(ObjC.classes.SecKeyWrapper.$ownMethods.join('\n'))` to list all the methods on this class.

**Comment by JohnWickJM** [comment]
This was of tremendous help and cleared some misunderstandings I had. One follow up, so if the doCipher is declared as 
(id)doCipher:(id)arg1 key:(id)arg2 context:(unsigned int)arg3 padding:(unsigned int *)arg4;
or 
(NSData *)doCipher:(NSData *)plainText key:(NSData *)symmetricKey context:(CCOperation)encryptOrDecrypt padding:(CCOptions *)pkcs7 { return nil; } 

Maybe an obvious question but how would you access the plainText using Frida?  I know you can do this in lldb and read the appropriate register etc...
