### ISSUE TITLE
Stalker API not yet available in the Duktape runtime

### ISSUE THREAD

**Issue by nevermoe** [frida/frida-core#112]
Hi, I am trying to use Stalker on iOS and Android but frida throw this error: "Stalker API not yet available in the Duktape runtime".

I searched for this error and found that you stated frida 9 is using Duktape as default. Can I by any change use Stalker in frida 9? If not, is there another way to track function calls or instruction calls? Sorry I'm not familiar with javascript.

Thank you!

**Comment by oleavr** [comment]
Hi,

You can always use the V8 runtime, or help us improve the Duktape runtime to support it (now that would be awesome!).

Cheers!
