### ISSUE TITLE
PTRACE_ATTACH Permission Denied (LineageOS 7.1.1)

### ISSUE THREAD

**Issue by kenoph** [frida/frida-core#123]
I just installed frida and I'm getting an error when I try to `frida-trace` an app.

Relevant `adb logcat`:

```sh
05-03 14:43:31.964  8088  8088 W frida-helper-32: type=1400 audit(0.0:548): avc: denied { sigchld } for scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:sudaemon:s0 tclass=process permissive=0
```

The server was running as `root`.

**Comment by Oreaz** [comment]
Try to set selinux to Permissive:
https://github.com/frida/frida-core/issues/63

**Comment by max01203** [comment]
Hi,
As he said you have to run frida using root and with selinux in permissive.
To do so run:
su 
setenforce 0

Thanks
