### ISSUE TITLE
How to print a value of the passed string reference in C++?

### ISSUE THREAD

**Issue by berkedel** [frida/frida-core#124]
How do I print the value of the third argument for this function?
```
CommonUtils::decodeCStringForBase64(char const*, char const*, std::string &)
```

Currently I can print the first and second argument by using `Memory.readUtf8String`.

**Comment by stek29** [comment]
I made a [post](http://stek29.rocks/2017/08/07/frida-stdstring) in my blog about it, if you still interested.

**Comment by berkedel** [comment]
@stek29 thanks for a detailed explanation. I will try it.

**Comment by stek29** [comment]
You may also want to check out @oleavr's [snippet](https://codeshare.frida.re/@oleavr/read-std-string/) on frida-codeshare (I added a note about it to post too)
