### ISSUE TITLE
stalker does not work on macos

### ISSUE THREAD

**Issue by dreamhaha** [frida/frida-core#131]
Hi,

Stalker does not work on macos with error "Stalker API not yet available in the Duktape runtime"

1:
I try to make with  FRIDA_DIET=no in config.mk  to enable v8, but the error still occured.

2:
I try to make with 
FRIDA_DIET_FLAGS := -Denable_diet=no
but still error

Help, please!

Thanks!

**Comment by oleavr** [comment]
Hi,

You also have to `session.enable_jit()` before creating the first script. (Or pass `--enable-jit` if it's a Frida CLI tool.) Most of our binaries, including those for macOS, are built with `FRIDA_DIET=no` though so no need to compile it yourself.

Cheers!

**Comment by jabyrd3** [comment]
@oleavr hey, sorry to bug you about this again, but i'm getting session.enable_jit() is not a function. When i log session.__proto__ i can see all the proper props for the session object (sans enable_jit, obviously), so i think i might be looking in the wrong place?
