### ISSUE TITLE
Failed to attach: failed to execute child process “/data/local/tmp/re.frida.server/frida-helper-32” when run "frida-trace -i "open" -U com.android.chrome" 

### ISSUE THREAD

**Issue by zheya08** [frida/frida-core#132]
Hi, I have an issue with Frida.
```
$ frida-trace -i "open" -U com.android.chrome
Attaching...
Failed to attach: failed to execute child process “/data/local/tmp/re.frida.server/frida-helper-32” (Permission denied)
```
frida-server path is ```/data/local/tmp```
Using Windows7 python2.7.13 and Galaxy S3 with Android 4.2.2 KingRoot

I list the file 
```
root@android:/data/local/tmp/re.frida.server # ll
-rwxr-xr-x root     root     11942668 2017-06-09 18:01 frida-agent-32.so
-rwx------ root     root      1836268 2017-06-09 18:01 frida-helper-32
```

and then i changed the permission 
```
chmod 777 frida-helper-32
```

but it does not work.

Would appreciate your help! :)

**Comment by oleavr** [comment]
Hi,

This is a known issue caused by a Samsung kernel patch. You can work around it by installing SuperSU, so Frida can talk to it and use it to spawn the process.

Cheers!
