### ISSUE TITLE
Tracing a call step by a step ?

### ISSUE THREAD

**Issue by Frantch** [frida/frida-core#133]
Is there a way with Frida to see the call flow considering that I know the address of a function ?
I'm trying to trace some API call in an android app I managed to get the address of a key function:

`send_request(String uri, AnObject anObject)`

I can hook into send_request and I can see the uri and the content of anObject

```
function_ptr = base_address.add(ptr("0x11e490c"))
Interceptor.attach(function_ptr, {
        onEnter: function(args) {
            console.log("arg0="+args[0] + " arg1="+args[1]+ " arg2="+args[2])
            ...hexdump etc..
        },
        onLeave: function(retval) {
        }
});

```
But now I would like to know where do the code goes after calling 0x11e490c. Is there a way to tell frida to output all the address AFTER (and before ?) having called 0x11e490c?

Thank you

**Comment by oleavr** [comment]
Hi,

This is possible by using the `Stalker` API, available on x86 (32- and 64-bit) and arm64 (but not 32-bit ARM for now): http://slides.com/oleavr/frida#/16

Your other option is to look at `this.returnAddress` from `onEnter` and use a static analysis tool, e.g. r2, to find other places to put probes manually. You can use instruction-level probes to hook in the middle of functions (see docs).

Cheers!

**Comment by Frantch** [comment]
Hello,

I did try stalker but it complained about something not being compatible with Duktape 'yet'

I didn't find anything in the doc that would allow me to switch to V8 for example.

Do I need to rebuild frida my self? (I had install it via pip on my mac)

**Comment by oleavr** [comment]
You can pass `--enable-jit` if you're using one of the Frida CLI tools, and `session.enable_jit()` if you're using the Python bindings.
