### ISSUE TITLE
Accessing ivars and arg tampering

### ISSUE THREAD

**Issue by darkknightjm** [frida/frida-core#134]
Hi,
So a couple quick questions:
1. How do you access/set instance variables in frida?

2. If this line
`console.log("PlainText: " + arg.toString());`

returns the following:

```
PlainText: {
    "some_id" = 100;
    offset = 0;
    "order_by" = id;
    uri = "/some/endpoint";
}
```
How do you set parameter "some_id" with frida?
P.S. Maybe this has already been answered and I missed it...

**Comment by oleavr** [comment]
Hi,

It's covered by the `new ObjC.Object()` docs [here](https://www.frida.re/docs/javascript-api/#objc) – use `$ivars`. You can use `Object.keys()` to get an array of possible ivar names that can be read/written. So that means `obj.$ivars.some_id = value` for your example.

Cheers!

**Comment by darkknightjm** [comment]
One clarification, if I call $ivars on the class i.e. arg[0], and then dump the keys thats fine. However if I call it on arg[2] i.e the argument to the function then it does not return the expected mapping of :
```
"   some_id" = 100;
    offset = 0;
    "order_by" = id;
    uri = "/some/endpoint";
```
So question number 2 was for those cases when the method accepts json like parameters...

**Comment by oleavr** [comment]
Are you talking about `NSDictionary`?

**Comment by darkknightjm** [comment]
So that output is what frida returns when you do a
`console.log("args: " + ObjC.Object(args[2]).toString() + "\n");`

I wanted to know how to modify those returned values....
