### ISSUE TITLE
firda-server build statically binary

### ISSUE THREAD

**Issue by ret5et** [frida/frida-core#138]
How I can do this?

**Comment by oleavr** [comment]
Change `executable` to `static_library` [here](https://github.com/frida/frida-core/blob/a54dff0836cd070f0319d01dafaf53d56c6ffaa1/server/meson.build#L35).

**Comment by ret5et** [comment]
Thanks! I will try it.

**Comment by ret5et** [comment]
I tryed but it is not worked for me. 
I what build frida-injector and frida-server as statically linked (-static-libgcc), but not as static so files.
I have old system with glibc-2.5 and therefore I cant use pre  build binares of frida. 
On the other hand I don't what  update whole system (oracle linux server 5.11) for new version of libc.

So how can I build frida-server  and frida-injector as "not a dynamic executables".

**Comment by ret5et** [comment]
I had got this error
'''
 warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
'''
It seems to me that compile firda-server as static library is not trivial.
