### ISSUE TITLE
firda-server as statically binary

### ISSUE THREAD

**Issue by ret5et** [frida/frida-core#139]
I want build frida-injector and frida-server as statically linked (-static-libgcc), but not as static a/o files.
I have old system with glibc-2.5 and therefore I cant use pre build binares of frida.
On the other hand I don't what update whole system (oracle linux server 5.11) for new version of libc.

So how can I build frida-server and frida-injector as "not a dynamic executables".

And I had got this wrnings
```
warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Any solutions?

**Comment by oleavr** [comment]
You could try tweaking the build settings here:
https://github.com/frida/frida-core/blob/master/server/meson.build

However, it's probably easier to set up a buildroot with an old libc and build Frida there.
