### ISSUE TITLE
Frida not working on Android 4.4.2 nexus 5

### ISSUE THREAD

**Issue by flankerhqd** [frida/frida-core#14]
Hi:

I tried the tutorial at http://www.frida.re/docs/android/, however I couldn't get it working. Running *frida-trace -R -i open com.android.chrome* just showing 

```Started tracing 0 functions. Press ENTER to stop.  ```

And no any output. I'm ensured the following conditions: 
1) /data/local/tmp/ is -R 777
2) getenforce is permissive
3) frida-server is running as root, and ports are forwarded.

Would you kindly give some hints? Thanks.

**Comment by flankerhqd** [comment]
Host machine ubuntu 12.04 x64

**Comment by flankerhqd** [comment]
Found working on OS X, seems only a Linux issue...

**Comment by oleavr** [comment]
Hey,

That is strange. Did you try `-i "open*"` to match any function starting with `open`? The code running on your host side in this case is, at the C/native layer, very simple; just opening a TCP connection to your device and exchanging messages with it. On the Python layer it is exactly the same code running on Linux and Mac, and that's also where the matching of functions happens.

Would be great to get to the bottom of this, as I'm about to wrap up on the next release.

Thanks!

**Comment by flankerhqd** [comment]
I found I was using frida 1.6.8 on my OS X, after upgrading to latest 2.2.0, OS X is not working neither, tracing 0 functions.  Using -i "open*" doesn't help.

I'm using OS X 10.10.2, Python 2.7.5

**Comment by oleavr** [comment]
Oh wow, great catch! Will investigate this for the upcoming release. I will keep you posted.

**Comment by oleavr** [comment]
This now be fixed in the just-released `3.0.1`. I'll announce the release soon, so please let me know if you find any further issues.

**Comment by flankerhqd** [comment]
Nice, thanks!
