### ISSUE TITLE
Frida Android Daemon API

### ISSUE THREAD

**Issue by brompwnie** [frida/frida-core#143]
Hi there,
Are there any existing resources no how to consume the Frida Daemon i.e API of sorts for the Daemon? If not, could you please point in the right direction?

**Comment by oleavr** [comment]
Hi,

Sorry for the delay. What do you mean by daemon API?

Some resources that might be relevant:
- [frida-server](https://github.com/frida/frida-core/blob/master/server/server.vala)
- [frida-core's API](https://gist.github.com/oleavr/e6af8791adbef8fbde06), which is what frida-server uses and simply exposes over peer-to-peer DBus.

Cheers!
