### ISSUE TITLE
Update JS engine in CLI

### ISSUE THREAD

**Issue by stek29** [frida/frida-core#149]
`frida` CLI is great for prototyping, and that's exactly why it'd be great to have (at least some of) ES6 features in it, like arrow functions and template literals.

<sub>having to type `function() { }` each time kills me</sub>

**Comment by oleavr** [comment]
Our default JS engine uses [Duktape](http://duktape.org/), so hopefully it will support this someday. The workaround, on platforms where V8 is available, is to use `--enable-jit` / `Session#enable_jit()`.

However, for complex agents I would recommend using [frida-compile](https://gist.github.com/oleavr/cae76c895eb7d227216ed3ffe9dbbeb3), as it supports the latest syntax, makes it easy to split your agent into multiple files through `require()`, and gives you access to thousands of existing modules from npm. (Some of which are Frida-specific.)

Cheers!

**Comment by stek29** [comment]
Thanks :)

for the reference: svaarala/duktape#275
