### ISSUE TITLE
Troubles with frida-trace on android emulator 4.3.1 on MacOS

### ISSUE THREAD

**Issue by VCibotaru** [frida/frida-core#15]
Hey!
First of all, thanks for such a great job! Frida is indeed a wonderful tool.

Now, on topic:
I try to run "frida-trace -p pid" to trace a process on my android emulator. I get the following error:
"Failed to attach: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: task_for_pid() for remote pid failed while trying to make pipe endpoints: (os/kern) failure (5)"

Frida-server is running on the device from /data/local/tmp with 777 rights on this folder. The ports are forwarded. 

Thanks in advance!

**Comment by oleavr** [comment]
Hi,




Thanks for the kind words!




You need to pass -R in order to use a remote device, otherwise it will be looking for that pid on your local system.




Cheers!



—

**Comment by VCibotaru** [comment]
It works, thanks!

**Comment by oleavr** [comment]
Glad to hear!
