### ISSUE TITLE
App crashes on Dalvik.perform on Android Emulator 4.3.1

### ISSUE THREAD

**Issue by VCibotaru** [frida/frida-core#16]
Hey!

I try to execute the following script on Android Emulator:

process = frida.get_remote_device().attach(processName)
script = process.create_script(jscode)
script.on('message', on_message)
script.load()
sys.stdin.read()

The jscode 'send(Dalvik.available') returns true.

Now, when i try to execute with jscode 'Dalvik.perform(function() {})' or Dalvik.perform(function() {send('1')}) the app gets crashed. 

Thanks in advance!

**Comment by oleavr** [comment]
Hi,

Thanks for the report! Is this in an ARM or x86 emulator?

Cheers!

**Comment by VCibotaru** [comment]
It`s an x86 emulator.
Everything works fine on ARM.

**Comment by oleavr** [comment]
Ahh right, sorry about that. I had a feeling that the Android/x86 port still needs some love before it can be considered usable. I'll remove the binaries for now to avoid confusing others. Thanks!

**Comment by VCibotaru** [comment]
Sorry for bringing the bad news(

**Comment by oleavr** [comment]
No I'm glad you made me aware of it, I had been thinking about it a while back and then forgot about it.
