### ISSUE TITLE
Failed to attach: timeout was reached

### ISSUE THREAD

**Issue by IdoBn** [frida/frida-core#163]
Running frida-server on an android emulator
Then running ```frida-ps -D <emulator identifier>``` works
However when running ```frida-trace -i "open" -D <emulator identifier> com.android.chrome```
I receive this error ```Failed to attach: timeout was reached```

frida-trace version 10.6.32
frida-ps version - 10.6.32
frida-server version - 10.6.32-android-x86

I'm running frida on Mac High Sierra  
The emulator is running android 7.0

**Comment by tautology0** [comment]
I get the same running on a rooted Nexus 5, running Android 6.0.1 (SELinux is set to permissive). Version 10.6.52, I'm running the client from Fedora Linux.

It times out on "Resolving functions...", gives the time out message, which causes the adb server to crash.

**Comment by luh2** [comment]
I get the same error on Win10 with a regular executable. 
frida-trace version 10.6.58.

**Comment by Lena900925** [comment]
Here the same:(

`frida-ps -U` works fine on Genymotion, but if I run
`frida-trace -U -i recv package.of.app`  I get:

> Attaching...
> Failed to attach: timeout was reached

I have frida version: 12.2.18

**Comment by kmille** [comment]
Same for me with frida-trace version 12.4.8 and a Nexus 5 (Lineage OS 14.1 / Android 7.1.2))

**Comment by kmille** [comment]
What worked for me is using 'setenforce permissive' before starting the frida-server

**Comment by RoyalFlushever** [comment]
@IdoBn 
Downgrade your frida-server version on your android devices.
For example, if you have frida-version 10.6.32 on your PC, you can install frida-server 10.0.X.
Note: only master version should match between frida-server and frida.

**Comment by nk9** [comment]
Ran into this problem on a jailbroken iPhone 6S running frida (on the desktop) frida-server (on the device) version 12.8.11. I upgraded both versions to 12.8.20 and attaching works again.

**Comment by MaeThird** [comment]
frida: 15.1.17
Android11
"reboot the mobile" or even "reboot the pc" or "setenforce permissive"  nothing works for me. 
Finally **start the frida-server with -P** works immediately.

**Comment by LucioDarcon** [comment]
@MaeThird I don't understand, can I tell you the command I used? 
I'm new using this tool

**Comment by j-kaltes** [comment]
I receive also this error message "_Failed to attach: timeout was reached_" from frida-trace
setenforce permissive  and starting frida-server with -P don't make a difference.

Running frida-server on LineageOS 20 (Android  13)
and frida-trace on Linux
frida-trace and frida-server version 16.6.3

When setenforce permissive isn't set, frida-server immediately gives the output:
```json
{"type":"error","description":"Error: invalid instruction","stack":"Error: invalid instruction\n    at Function.value (frida/runtime/core.js:481:1)\n    at Tn (frida/node_modules/frida-java-bridge/lib/android.js:1748:1)\n    at frida/node_modules/frida-java-bridge/lib/android.js:1626:1\n    at Object.value [as patchCode] (frida/runtime/core.js:227:1)\n    at In (frida/node_modules/frida-java-bridge/lib/android.js:1625:1)\n    at vt (frida/node_modules/frida-java-bridge/lib/android.js:579:1)\n    at frida/node_modules/frida-java-bridge/lib/memoize.js:4:1\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:574:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)","fileName":"frida/runtime/core.js","lineNumber":481,"columnNumber":1}
```
Followed by "_Illegal instruction_"
When  _setenforce permissive_ is set, frida-server gives after some time the same output, without "_Illegal instruction_"
