### ISSUE TITLE
(Android )frida -U -f  (-f parameter problem)

### ISSUE THREAD

**Issue by berkayyildi** [frida/frida-core#171]
I need to use -f because I want to connect on start directly but -f parameters causes error:
Failed to spawn: unexpectedly timed out while waiting for app to launch
Application successfully starting but frida shows error!
(Galaxy s6 Android 7.0)
Thanks.

**Comment by diegomanri** [comment]
Same for me. Same phone and Android version as you @berkayyildi

**Comment by bihihinok** [comment]
Same here @berkayyildi  @diegomanri , check issues #575 and #576

**Comment by berkayyildi** [comment]
@diegomanri Hi, I forgot which error did I get here but If you get error Failed to attach: failed to execute child process or Failed to Spawn: failed to execute child process

You should follow these steps:
// You should move frida to /system/priv-app and launch it from there.
su
mount -o rw,remount /system
mv /data/local/tmp/frida-server /system/priv-app
chown root:root /system/priv-app/frida-server
chmod 733 /system/priv-app/frida-server
mount -o ro,remount /system
 
//Go into /system/priv-app and run it
cd /system/priv-app
./frida-server-xxx-android-arm64 &

**Comment by oleavr** [comment]
A bug with this exact symptom has just been fixed in 306e288 -- currently being released in Frida 12.0.8. The original bug report is pretty old so let's close this.
