### ISSUE TITLE
Is there plugin for Frida through which we can load pdb file of an application?

### ISSUE THREAD

**Issue by cyberinferno** [frida/frida-core#172]
For example IDA Pro allows you to load Program Debug Database (pdb) file through which function names are automatically renamed into a human-friendly name. Is there such a tool currently for Frida? If not will it be added as a feature request into Frida? It will be an amazing feature because the reverse engineer can then just hook into the function using its name rather than its address!

**Comment by oleavr** [comment]
Check out the [DebugSymbol](https://www.frida.re/docs/javascript-api/#debugsymbol) API. Definitely interesting to expand this API further – PRs welcome!
