### ISSUE TITLE
Build issues on RHEL(FAILED: json-glib/json-enum-types.h)

### ISSUE THREAD

**Issue by bkavita** [frida/frida-core#179]
Compiler for C supports argument -Wl,-z,now: YES
Configuring config.h using configuration
Program glib-mkenums found: YES (/home/kavita/frida/build/fs-toolchain-linux-x86_64/bin/glib-mkenums)
Configuring json-version.h using configuration
Program xsltproc found: YES (/usr/bin/xsltproc)
Build targets in project: 33
Found ninja-1.7.2 at /home/kavita/frida/build/fs-toolchain-linux-x86_64/bin/ninja
(. build/fs-env-linux-x86_64.rc && ninja -C build/fs-tmp-linux-x86_64/json-glib install)
ninja: Entering directory `build/fs-tmp-linux-x86_64/json-glib'
[5/67] Generating json-enum-types.h with a meson_exe.py custom command.
FAILED: json-glib/json-enum-types.h
/usr/local/bin/python3 /home/kavita/frida/releng/meson/meson.py --internal exe /home/kavita/frida/build/fs-tmp-linux-x86_64/json-glib/meson-private/meson_exe_glib-mkenums_305f428e770d7b69a91b6a12c5ad04b720ea21a4.dat
/usr/bin/env: /opt/python27-64/bin/python: No such file or directory
[7/67] Generating invalid.test with a custom command.
ninja: build stopped: subcommand failed.
make: *** [build/fs-linux-x86_64/lib/pkgconfig/json-glib-1.0.pc] Error 1

**Comment by oleavr** [comment]
Please retry with a clean git clone – lots of changes happening this weekend.

**Comment by bkavita** [comment]
I had tried several times with a clean git clone before logging this issue. Tried once more with clean git clone. Here's the screenshot:
![image](https://user-images.githubusercontent.com/20150479/38174027-4cbb85d2-35e4-11e8-9885-2abece90cb40.png)

**Comment by oleavr** [comment]
Why are you trying to rebuild the SDK, and how are you doing it?

**Comment by bkavita** [comment]
For my study project, I need to rebuild the core. If I try to build the core its says build sdk. The command I had used - make -f Makefile.sdk.mk.

**Comment by stevielavern** [comment]
To solve the issue, edit `build/fs-toolchain-linux-x86_64/bin/glib-mkenums` and `build/toolchain-linux-x86_64/bin/glib-mkenums` and change the 1st line of both files to: 
```
/usr/bin/env python
```

**Comment by oleavr** [comment]
Nice catch @stevielavern – would love a PR improving `releng/setup.py` to take care of patching those.

**Comment by r0ck3tAKATrashPanda** [comment]
@oleavr Can you provide any insight into where fs-toolchain-* and toolchain-* are being generated. The only place I can find the string is in releng/release.py and that has no changes. I assume this is being code-gened somewhere, I am just having a hard time tracking down where. Also what is releng/setup.py. I do not see that file anywhere

**Comment by oleavr** [comment]
@r0ck3tAKATrashPanda The toolchain is generated by `Makefile.toolchain.mk`.
