### ISSUE TITLE
[Electra] Unable to spawn apps using dyld3

### ISSUE THREAD

**Issue by AeonLucid** [frida/frida-core#193]
Same issue as #176, but for newer versions.

**Device:** iPhone 6
**iOS version:** 11.3.1
**Jailbreak:** Electra-mptcp
**Frida tools & server**: 12.0.3

(1) Commands:
- `frida-ps -U -f com.apple.DocumentsApp` (Stock Files app)
- `frida-ps -U -f com.toyopagroup.picaboo` (Snapchat)

Result:
```
Failed to spawn: unexpectedly timed out while waiting for process to suspend
```

(2) Commands after the above error while keeping the spawned app open:
- `frida-ps -U -n Files`
- `frida-ps -U -n Snapchat`

Result:
```
Failed to attach: unexpected error while probing dyld of target process
```

_If you open the app manually, it attaches fine at (2)._

**Comment by xnamurt** [comment]
I've the same issue

**Comment by ChiChou** [comment]
👍

**Comment by mrmacete** [comment]
it's because hardware breakpoints don't work from iOS 11.3.1 up to and including iOS 11.4.1

we currently rely on hardware breakpoints for spawn and early instrumentation on i/macOS

currently working on implementing software breakpoints for those iOS versions

**Comment by bihihinok** [comment]
@oleavr what about android , please check issue #575 , #576
