### ISSUE TITLE
Child gating not working for sub-processes 

### ISSUE THREAD

**Issue by alexey-v-paramonov** [frida/frida-core#204]
Here is a simple code of a target process to demonstrate the problem:
```
void forkexample()
{
  int childpid = fork();
  if (childpid == 0)
    {
      printf("[CHILD] PID: %d \n", getpid());
      int childchildpid = fork();
      if(childchildpid == 0){
        printf("[GRANDCHILD] PID: %d \n", getpid());
        while(1){
          printf("[GRANDCHILD] I am alive with PID: %d\n", getpid());
          sleep(5);
        }
      }
      else{
        printf("[PARENT-CHILD] Created a new grandchild with PID: %d \n", childchildpid);
      }
    }
  else
    {
      printf("[PARENT] Created a new child with PID: %d \n", childpid);
      sleep(60000);
    }
}
int main()
{
  printf("Process ID:  %d\n", getpid());
  forkexample();
  return 0;
}

```
it forks a process and forks another one from inside the forked one.
When I try to attach Frida (with child gating enabled) to this example process it does attach and I can catch "child-added" signal fired by the first fork, but "child-added" not working for sub-process.

**Comment by oleavr** [comment]
Did you also enable child gating for each of the children before calling `resume()`?

**Comment by alexey-v-paramonov** [comment]
Thanks for the help, everything works well after I have enabled child gating for all child processes.
