### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Laura055** [frida/frida-core#206]
Hello!

When starting the frida-server I'm getting this: 

```
root@SM-G925F:/ # getprop dhcp.eth0.ipaddress
10.0.2.15
root@SM-G925F:/ # /data/local/tmp/frida-server -l 10.0.2.15:21502 &
[1] 4171
root@SM-G925F:/ # /system/bin/sh: /data/local/tmp/frida-server: can't execute: Permission denied
```

Someone told me to start the cmd console with admin privileges, I did that already and get the same error somehow. Is there a solution for this?

Thanks in advance!

**Comment by Laura055** [comment]
I fixed it myself, thanks anyways :)

**Comment by QueueDoubleU** [comment]
@Laura055 could you post your solution for anyone else with the error?

**Comment by thejunkjon** [comment]
chmod +x ./frida-server

**Comment by KevinGuancheDarias** [comment]
In my case even after applying chmod I was getting the access denied message, It pointed out to be due to some strange behavior of the file system, my frida-server binary was in the directory `/storage/1904-1FC2/frida-server`  , I moved it to `/data/local/tmp` and now it's working

**Disclaimer:** I'm using android emulator, not a real device

**Comment by christiancoleman** [comment]
> In my case even after applying chmod I was getting the access denied message, It pointed out to be due to some strange behavior of the file system, my frida-server binary was in the directory `/storage/1904-1FC2/frida-server` , I moved it to `/data/local/tmp/frida-server` and now it's working
> 
> **Disclaimer:** I'm using android emulator, not a real device

This helped me. I had been running it fine in /sdcard/Download a couple years ago but it started throwing this error recently even with the chmod +x which I do as part of normal install. Coping and running it in /data/local/tmp fixed it for me. Thank you!
