### ISSUE TITLE
SELINUX

### ISSUE THREAD

**Issue by craftalpian** [frida/frida-core#210]
My command : adb shell "/data/local/tmp/frida-server-12 &"
And output : "Unable to load SELinux policy from the kernel: Failed to open file “/sys/fs/selinux/policy”: Permission denied"

Im using windows 10.

**Comment by oleavr** [comment]
You need to run frida-server as root.

**Comment by ebraheemijaz** [comment]
I have run frida-server as a root (rooted devices samsung A7) but still facing this issue  output : "Unable to load SELinux policy from the kernel: Failed to open file “/sys/fs/selinux/policy”: Permission denied" please help

**Comment by ebraheemijaz** [comment]
I  am also facing the same issue with rooted

**Comment by Jahanzaeb** [comment]
@oleavr we are facing same issue as mentioned above we are runing frida server as root on [Samsung galaxy A710FD) but facing same error :
"Unable to load SELinux policy from the kernel: Failed to open file ΓÇ£/sys/fs/selinux/policyΓÇ¥: Permission denied"
Please guide me how I can fix this issue?

**Comment by oleavr** [comment]
@Jahanzaeb That means Samsung has restricted access to the running kernel's SELinux policy, so not even root can read/modify it. Either you will need to find a way to bypass that, or a way to disable SELinux. Worst-case you will need to build a new kernel, or patch the one you have using a hex editor.

**Comment by oleavr** [comment]
A third option is to locate the binary policy that your device is loading on boot, and patch it to add the rules that Frida attempts to insert automatically. But this is probably quite tricky to do.

**Comment by Josue198s** [comment]
> You need to run frida-server as root.

That means the device must be rooted.

**Comment by kiranAndr** [comment]
[This comment](https://github.com/frida/frida/issues/597#issuecomment-627772251) worked for me

**Comment by LucasGinard** [comment]
[this comment](https://github.com/frida/frida/issues/597#issuecomment-640057942)  works in Samsung A50 Android 11 with magisk
