### ISSUE TITLE
rida_get_regs returned 'I/O error'

### ISSUE THREAD

**Issue by marc1006** [frida/frida-core#23]
When I'm trying to attach to a process the error
> Failed to attach: unexpected error while attaching to process with pid 4786 (frida_get_regs returned 'I/O error')

occurs.

For some reasons PTRACE_GETREGSET doesn't work for me.
https://github.com/frida/frida-core/blob/9eda2d55ebd8f07c5894c93b7198733c8def2448/src/linux/frida-helper-glue.c#L925
Maybe also https://github.com/frida/frida-core/blob/9eda2d55ebd8f07c5894c93b7198733c8def2448/src/linux/frida-helper-glue.c#L935
WIth the old version ```ret = ptrace (PTRACE_GETREGS, pid, NULL, saved_regs);``` it works.

SELinux is set to permissive and the OS is Android 4.4.4.

**Comment by oleavr** [comment]
Oops. This should hopefully be fixed now starting with 368b51d63945bc8d338b7f9caa99f0bc286f367e, and the binary at build.frida.re has been updated. Please let me know if it works now.

Thanks for reporting!

**Comment by marc1006** [comment]
It works :) Thanks!
