### ISSUE TITLE
SpawnMonitor will not disabled by release_child_gating

### ISSUE THREAD

**Issue by gebing** [frida/frida-core#243]
If a spawn related function call, such as `execvp`, is called directly after calling `fork`, the `SpawnMonitor` will not disabled because of the asynchronous `release_child_gating` does not take effect yet, just like the implement of Android's `Runtime.exec`.

So in function `finish_recovery_from_fork` of 'agent.vala`, the call of `release_child_gating` should be placed before `wait_for_permission_to_resume`, just like following code:

```
private async void finish_recovery_from_fork (ForkActor actor, string? identifier) {
	// move to here
	if (actor == CHILD)
		release_child_gating ();

	if (actor == CHILD && controller != null) {
		var info = HostChildInfo (fork_child_pid, fork_parent_pid, ChildOrigin.FORK);
		if (identifier != null)
			info.identifier = identifier;

		try {
			yield controller.wait_for_permission_to_resume (fork_child_id, info);
		} catch (GLib.Error e) {
			// The connection will/did get closed and we will unload...
		}
	}

	fork_parent_pid = 0;
	fork_child_pid = 0;
	fork_child_id = HostChildId (0);
	fork_parent_injectee_id = 0;
	fork_child_injectee_id = 0;
	fork_child_socket = null;

	fork_mutex.lock ();
	fork_recovery_state = RECOVERED;
	fork_cond.signal ();
	fork_mutex.unlock ();

	// remove from here
	// if (actor == CHILD)
	//	release_child_gating ();
}
```

**Comment by oleavr** [comment]
The reason we do it after is so the Frida-based application has the ability to `enable_child_gating ()`, making our `release_child_gating ()` a no-op. (So the hooked APIs can remain hooked, and don't have to be reverted and immediately re-hooked right after.)

However if we move the call to right before `fork_parent_pid = 0;`, wouldn't that solve the problem without causing a performance regression?

**Comment by gebing** [comment]
i moved `release_child_gating ()` to right before `fork_parent_pid = 0` and tested, it works ok.

**Comment by oleavr** [comment]
@gebing Awesome. JustcCommitted that change attributed to you. Thanks!
