### ISSUE TITLE
linux resume 32bit vs 64bit cpu_type mixup?

### ISSUE THREAD

**Issue by r4xjs** [frida/frida-core#262]
Hi,
just wanted to ask if the following code in frida-core/src/linux/frida-helper-process.vala shouldn't be reversed, see comments:
```
        public async void resume (uint pid, Cancellable? cancellable) throws Error, IOError {
            var cpu_type = cpu_type_from_pid (pid);
            var helper = yield obtain_for_cpu_type (cpu_type, cancellable);
            try {
                yield helper.resume (pid, cancellable);
            } catch (Error e) {
                if (!(e is Error.INVALID_ARGUMENT))
                    throw e;
                if (cpu_type == Gum.CpuType.AMD64 || cpu_type == Gum.CpuType.ARM64)
                    helper = yield obtain_for_32bit (cancellable);   // shouldn't this be: obtain_for_64bit?
                else
                    helper = yield obtain_for_64bit (cancellable);   // and this: obtain_for_32bit?
                yield helper.resume (pid, cancellable);
            }
```
I noticed the following error during resume on a 32bit android process with frida-server-12.7.3-android-arm:
```
    self._device.resume(pid)
  File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 148, in resume
    self._impl.resume(self._pid_of(target))
NotSupportedError: unable to handle 64-bit processes due to build configuration
```

**Comment by oleavr** [comment]
No, that code deals with e.g. a 64-bit process becoming 32-bit after an `execve()`.

The issue you're running into is usually caused by running the 32-bit ARM frida-server instead of the arm64 one, on a 64-bit ARM system.

**Comment by r4xjs** [comment]
Thank you for the quick response, I will investigate further. Seems odd, this is executed on a Nexus 5 with android 6.0 stock rom.

**Comment by r4xjs** [comment]
Update: found the reason to the above problem. device.resume(pid) should only be called if device.spawn(..) was used before. Just a mistake in my modified script.
Thank you again for the great tool :-)
