### ISSUE TITLE
The android gadget error on 12.8.6 

### ISSUE THREAD

**Issue by YuriSizuku** [frida/frida-core#285]
The frida in python shows 12.7.23, and it works on 12.7.23 gadget. But when I chose the gadget version to 12.8.6 arm, it didn't work. Also logcat show nothing, the application freeze with white screen. (It works when I using 12.8.6 server).

**Comment by oleavr** [comment]
Thanks for reporting everyone. Currently releasing 12.8.8 with the fix for this issue.
