### ISSUE TITLE
[iOS] Signed app crashing with frida gadget > 12.8.7

### ISSUE THREAD

**Issue by ddzobov** [frida/frida-core#289]
Hello!

Just updated frida gadget to 12.8.9 - app stucked in launch screen and after crashes.

iOS 13.3, iPhone 7 Plus

But i can run it via
`ios-deploy --bundle "Payload/DJI GO 4.app" -W -d -m`

Downgraded to 12.8.8 - same behavior
Downgraded to 12.8.7 - launched

**Comment by oleavr** [comment]
Thanks for reporting – great catch! Releasing 12.8.10 right now with the fix.

**Comment by ddzobov** [comment]
Thank you, all works perfectly. 

Frida is awesome, many thanks for your work!
