### ISSUE TITLE
Generated VAPI doesn`t have Error type

### ISSUE THREAD

**Issue by kirill9617** [frida/frida-core#298]
When trying to use shere/vala/vapi/frida-core-1.0.vapi I got bunch of errors like this:
> frida-core-1.0.vapi:297.101-297.111: error: The type name 'Frida.Error' could not be found
>                public void recreate_thread_sync (uint pid, uint id, GLib.Cancellable? cancellable = null) throws Frida.Error, GLib.IOError;
 >         ^^^^^^^^^^^

I suppose VAPI missing somthing like
```	
public errordomain Error {
		SERVER_NOT_RUNNING,
		EXECUTABLE_NOT_FOUND,
		EXECUTABLE_NOT_SUPPORTED,
		PROCESS_NOT_FOUND,
		PROCESS_NOT_RESPONDING,
		INVALID_ARGUMENT,
		INVALID_OPERATION,
		PERMISSION_DENIED,
		ADDRESS_IN_USE,
		TIMED_OUT,
		NOT_SUPPORTED,
		PROTOCOL,
		TRANSPORT
	}
```

**Comment by oleavr** [comment]
Thanks for reporting – great catch!
