### ISSUE TITLE
Is there a way to modify the name of frida-agent.so?

### ISSUE THREAD

**Issue by FinchZ** [frida/frida-core#310]
Some app can check /proc/self/maps.When matching frida, it will quit.
I hope I can edit a config file to realize it.

**Comment by KenjiroIchise** [comment]
If you need such a feature, I highly recommend you to build Frida on your own.
It only takes a few lines to rewrite the name of the loaded frida-agent.

**Comment by oleavr** [comment]
A hex editor or an r2pipe script will also do the trick – the `frida-server` binary is self-contained with all assets in uncompressed form, so you can easily search-replace identifiers without recompiling.
