### ISSUE TITLE
 How to print NSConcreteMutableData

### ISSUE THREAD

**Issue by lijiaxing1997** [frida/frida-core#319]
I hooked to a piece of data and found that it was of NSConcreteMutableData type, and directly printed and displayed <352b574b 2b423244 67734d70.... How should I print?

**Comment by oleavr** [comment]
Check out our NSData examples at:
https://frida.re/docs/examples/ios/

**Comment by lijiaxing1997** [comment]
Hello, your answer is very helpful to my work. But now I have a new problem, the data type I hooked is _NSInlineData:<86715a3e ecb0d842..., I use bytes().readUtf8String() to report this data type. It is displayed as "Error: can't decode byte 0x86 in position 0\n". How to print data like this that is not a standard data structure?
