### ISSUE TITLE
How to print _NSInlineData？

### ISSUE THREAD

**Issue by lijiaxing1997** [frida/frida-core#321]
Hello, your answer is very helpful to my work. But now I have a new problem, the data type I hooked is _NSInlineData:<86715a3e ecb0d842..., I use bytes().readUtf8String() to report this data type. It is displayed as "Error: can't decode byte 0x86 in position 0\n". How to print data like this that is not a standard data structure?

_Originally posted by @lijiaxing1997 in https://github.com/frida/frida-core/issues/319#issuecomment-643088078_

**Comment by oleavr** [comment]
Something like:

```js
var buf = data.bytes().readByteArray(data.length());
console.log(hexdump(buf, { ansi: true }));
```
