### ISSUE TITLE
Add support for listing Android apps

### ISSUE THREAD

**Issue by radare** [frida/frida-core#33]
My guess is that android can reuse firefoxos app loop and just check if /proc/pid/exe points to `/system/bin/app_process`. This will give us the appid and pid, but i don't see a clear path to retrieve app name without parsing the apk which will require adding more deps to Frida. Is there any other way to make that listing?

**Comment by oleavr** [comment]
Not aware of any way to get the name beside that, but hopefully there is something we haven't though about.
