### ISSUE TITLE
Disable iOS Crash Report Symbolication

### ISSUE THREAD

**Issue by jiska2342** [frida/frida-core#345]
Hi,

I have some weird issues only on my two iPhone 8 again :) Nothing that happens on the iPhone 6, 7 or 11...

...it seems that crash logs that were symbolicated by Frida are missing thread names, at least quite often. If they are not symbolicated, the same crashes always have thread names, even if they end on `.forced-by-frida`.

What is the best option to disable symbolication and debug if this really is causing my issues? Recompile `frida-server` without [reportcrash.js](https://github.com/frida/frida-core/blob/36d64a94392408a80c914e9c1960c23dcbdd8bb8/src/darwin/agent/reportcrash.js)? Or is there an easier option, i.e., somehow unloading it during runtime?

Best,
Jiska

**Comment by oleavr** [comment]
Hey,

for now you will have to disable it by patching the code.

1) Add an early return [here](https://github.com/frida/frida-core/blob/a84f7bbc6d5890c87d97cc9bf46daa4fbc3b66b8/src/darwin/darwin-host-session.vala#L501).
2) Make [this](https://github.com/frida/frida-core/blob/a84f7bbc6d5890c87d97cc9bf46daa4fbc3b66b8/src/darwin/agent/launchd.js#L6-L9) an empty object.

Cheers!

**Comment by jiska2342** [comment]
Just tried it and it works, finally have thread names in my iPhone 8 crash logs again :)

I also noticed the same behavior in a few iPhone 7 crash logs meanwhile, for whatever reason it does not happen that often on it... And the Frida symbolication is missing backtraces, which are included in those crashes that are caused by uncaught exceptions, I think.

Symbolication is really a nice feature anyway, since my other workflow requires copying them to macOS ;)  Making this some configuration option or external tool would be great, at least for those who are fuzzing things that are so complex that exceptions typically cannot be caught properly.
