### ISSUE TITLE
Frida spawn doesn't work on Android ARM64/Aarch64 anymore

### ISSUE THREAD

**Issue by bkerler** [frida/frida-core#346]
It seems that spawning an Android app doesn't work with 14.0.1 under Aarch64 anymore, whereas it worked fine with 12.x versions. Also "frida-ps -U" doesn't list all running processes anymore like "com.facebook.katana" with 14.0.1.

Here's a log : 

```
bjk@bjk:~/Projects$ frida -U -f it.ideasolutions.kyms
     ____
    / _  |   Frida 14.0.1 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Failed to spawn: unexpectedly timed out while waiting for app to launch 
bjk@bjk:~/Projects$ 
```

**Comment by bkerler** [comment]
Because I forgot to mention: Device is rooted unlocked Oneplus 8 Pro with Android 10, frida-server-arm64 is started manually as daemon.

**Comment by oleavr** [comment]
Thanks for reporting!  Is the server running as root?

**Comment by bkerler** [comment]
Yes of course. Full root rights with selinux context disabled. Hooking without spawning works fine with latest frida, but if you spawn the app the app gets restarted (as it should) and frida just waits and times out, unlike older versions that work fine.

**Comment by idenchik1** [comment]
Same issue, rooted ASUS ZenFone Max Pro M2, SELinux permissive, run as root from ADB
![image](https://user-images.githubusercontent.com/34679695/100622205-2e7a4800-3353-11eb-8623-a297291fb963.png)

**Comment by oleavr** [comment]
@idenchik1 Is USAP enabled? Frida is not yet compatible with it. You can disable it by changing `persist.device_config.runtime_native.usap_pool_enabled`.

**Comment by bkerler** [comment]
My client is Android 6 based phone with no usap, no selinux, no seccomp. 12.x works fine. 14.x is unstable, doesn't hook all the time and spawn times out.

**Comment by bkerler** [comment]
So far tested three devices (Android 6, Android 8 and 10), BQ x5, oneplus 6t and 8 pro), all having the same results.

**Comment by hpr** [comment]
also having this issue on a oneplus 7 pro, lineageOS with microG based on android 10 w/ `setenforce 0` -- i remember being able to spawn processes a few months ago with frida 12.x on the same device (albeit with a different custom ROM), though now if i try to install old versions of frida-server/frida-tools on this OS i'm still getting the same "Failed to spawn: unexpectedly timed out while waiting for app to launch" error. 

hooking to already-running processes seems to work OK though.

**Comment by almightywizard** [comment]
Anyone managed to get it work? I'm having the same problem on oneplus5t. Frida-server is run as root, able to attach to any running processes, with -f flag on, the app spawned but frida stuck at "Failed to spawn: unexpectedly timed out while waiting for app to launch".

**Comment by bkerler** [comment]
Try setting this on your phone :  'setprop persist.device_config.runtime_native.usap_pool_enabled false'

**Comment by javieral-baihaqi** [comment]
> Try setting this on your phone : 'setprop persist.device_config.runtime_native.usap_pool_enabled false'

**Comment by FuentesFelipe** [comment]
'setprop persist.device_config.runtime_native.usap_pool_enabled false' **works**. Thanks!.

**Comment by harsh-im** [comment]
I am not able to set `'setprop persist.device_config.runtime_native.usap_pool_enabled false` in a rooted samsung device

**Comment by cxzero** [comment]
@harsh-im check that you are running the command as root. 
If using Magisk for example, grant superuser grant to com.android.shell.

```
su
setprop persist.device_config.runtime_native.usap_pool_enabled false
``` 

Then `getprop | grep usap` to see if it was modified.

**Comment by D0ntTrustMe** [comment]
Hi, 
Any update about this ? 
Same issue with my OnePlus8 Pro (Android 13), Magisk 27.0 and latest frida version ([16.4.7 actually)

Tried to 
su
setprop persist.device_config.runtime_native.usap_pool_enabled false 

But same issue.
