### ISSUE TITLE
frida doesn't work on Apple M1

### ISSUE THREAD

**Issue by geodidi** [frida/frida-core#351]
Device : MacBook Pro (13-inch, M1, 2020)
frida version : Frida 14.1.2
os : macos big sur 11.0.1

Hi!
I tried to attach a process, it was failed.
For example:
```
 frida -p 409
     ____
    / _  |   Frida 14.1.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Failed to attach: unable to bind, “_fstat$INODE64” not found in “/usr/lib/libSystem.B.dylib”
```

**Comment by oleavr** [comment]
@geodidi Thanks for reporting. Curious why this was closed? What was the target process? Was it an iOS Simulator or x86_64 process perhaps?

**Comment by geodidi** [comment]
> @geodidi Thanks for reporting. Curious why this was closed? What was the target process? Was it an iOS Simulator or x86_64 process perhaps?

sorry,before I installed frida on python3.7 x86_64, now i changed to python3.8 arm64e.
