### ISSUE TITLE
Separate out inject library

### ISSUE THREAD

**Issue by xiaozhuai** [frida/frida-core#354]
I'm the author of [odourless](https://github.com/xiaozhuai/odourless) (A tool for preventing .DS_Store creation)
I use mach_inject and frida-gum in odourless. It works well. Thanks very much!
Recently I found mach_inject not working on MacOS Big Sur and I decide to change to frida-core injector.
But frida-core has very big size. I am looking for something smaller.
Inject a dylib to a process by pid is enough for me. 
It will be nice if we can separate out inject library.
Thanks!

**Comment by oleavr** [comment]
Hi!

Great use-case, very cool!

Did you try `frida_injector_new_inprocess()`? (And giving your executable the appropriate entitlements.) Together with the linker's tree-shaking this should give you binaries as small as if it were a separate library.

Cheers!

**Comment by xiaozhuai** [comment]
Hi @oleavr 
I've replace `mach_inject` with `frida-core` in latest odourless version 0.0.8.
It works well on Big Sur!
Also I set `set(CMAKE_EXE_LINKER_FLAGS "-s -Wl,-dead_strip ${CMAKE_EXE_LINKER_FLAGS}")` to strip the binary and it's size reduce form 30+MB to 5MB.
