### ISSUE TITLE
Getting key and iv from CCCrypt

### ISSUE THREAD

**Issue by tosbaha** [frida/frida-core#36]
I am playing with frida and I tried to intercept key and IV of CCCrypt on iOS. I can read the key with 
```javascript
var key = Memory.readUtf8String(args[3]);
```
if the key is a string. If lets say it is some non ASCII, I can't print it. I tried
```javascript
var keyDump = Memory.readByteArray(args[3], 32); 
```
but it gives
[object Object]
Using below code gives me first bytes of key in reverse order
```javascript
var keyPointer = Memory.readPointer(args[3]);
```

**Comment by oleavr** [comment]
The value returned by `Memory.readByteArray()` behaves like an array with JavaScript numbers, e.g. "\x01\x02\x03" is the equivalent of `[1, 2, 3]`.

The recommended approach is:

```JavaScript
var keyDump = Memory.readByteArray(args[3], 32);
send({ ... }, keyDump);
```

where your keyDump is provided as the second argument of your message callback on the host side. You could also put it inside the message (first argument to send()) by Base64-encoding it.

**Comment by tosbaha** [comment]
I am using frida-trace and auto generated CCCrypt.js. Could you tell me how can I print keyDump on to the console by using log() function as hex array. Something like [0xaa,0xbb...] My current approach is having a loop on pointer and reversing etc which is cumbersome.Example

```javascript
for (var i = 0; i !== 8; i++) {
  var p = args[3].add(i*4);
 temp = Memory.readPointer(p).toString();
log(temp);
}
```
PS: I will really appreciate, if you can update the documentation with more examples. It is really hard to dig into news section of frida's home page to understand what is what. 
PPS: Also on iOS if name of application contains some none ASCII character such as ```Ş``` frida-trace can't attach to that process. Although frida allows spawning process by using bundle identifier, it doesn't allow attaching by bundle identifier. I wish we could attach bu bundle identifier.

**Comment by oleavr** [comment]
Ok. Try this:

```JavaScript
var rawKey = Memory.readByteArray(args[3], 32);
var key = '';
for (var i = 0; i !== rawKey.length; i++)
  key += rawKey[i].toString(16);
log('Key: ' + key);
```

Been meaning to add more examples to the documentation, but I haven't been able to prioritize this kind of work as there have been more important things keeping me busy. If you feel like opening PRs against frida-website as you learn new things, that would be awesome!

Regarding attaching, you can attach by pid, and just look at the output of `frida-ps -Ua` to determine the pid of the app you're interested in.

**Comment by tosbaha** [comment]
Thanks for the code. Unfortunately my skills are limited both on Objective C and javascript. I even couldn't print contents of NSString. I found one example on "issues" section but because it was using old notation I couldn't make it work. I hope when you finish the things that keep you busy, you or other project contributors, write some hands-on examples to show the power of this tool kit. Thanks again for your awesome project and keep up the good work.

**Comment by oleavr** [comment]
The Objective-C integration has been improved quite a bit since this issue was opened. We'll keep working on the documentation though, it still needs quite some work. Thanks for your feedback!

**Comment by hellofrida** [comment]
var rawKey = Memory.readByteArray(args[3], 16);
			var key = '';
			for (var i = 0; i !== rawKey.length; i++) {
			 // key += rawKey[i].toString(16);
			 
			 //console.log(rawKey[i].toString(16));
			 if(rawKey[i].toString(16).length == 1) {
				 key += '0';
				}
				key += rawKey[i].toString(16);
			
			}
