### ISSUE TITLE
Support iOS devices connected wirelessly

### ISSUE THREAD

**Issue by Manouchehri** [frida/frida-core#362]
Would be nice if we could add support for devices connected wireless. It seems that the device info can be obtained through usbmuxd, and then we can connect directly to the networked device.

https://github.com/libimobiledevice/libimobiledevice/blob/26d7d4a0b1bc12d88f38630ab14135f9dadc1be5/src/idevice.c#L437-L485

Thank you to @nicolas17 for pointing this out.

**Comment by oleavr** [comment]
This is finally supported as of 15.0.0 🎉
