### ISSUE TITLE
Failed to spawn: unexpectedly timed out while waiting for app to launch

### ISSUE THREAD

**Issue by 2735106525** [frida/frida-core#376]
Hi!
Android v10
In Frida 14.2.18 i have same problem - Failed to spawn: unexpectedly timed out while waiting for app to launch.
![image](https://user-images.githubusercontent.com/62138736/120370956-c8916c00-c347-11eb-9e91-0c22d9668261.png)

**Comment by 2735106525** [comment]
ps:but I can run it on the Android emulator

**Comment by javieral-baihaqi** [comment]
i cant in android why?same issue

**Comment by 2735106525** [comment]
已经解决了,初步怀疑是国内安卓系统的问题,刷机换成类原生解决掉了
It has been solved. It is suspected to be the problem of the domestic Android system,Use protogenesis Android

**Comment by 2735106525** [comment]
![image](https://user-images.githubusercontent.com/62138736/120524685-e7f0cd80-c409-11eb-928c-5a3c6c3769a7.png)

**Comment by chouex** [comment]
also reproduce this  issue on oneplus 8T with stock rom + magisk(hide disabled),  work find on oneplus3T with LineageOS .
but I was able to use `-F` to attach existing process.

    / _  |   Frida 14.2.18 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Failed to spawn: unexpectedly timed out while waiting for app to launch


tried Frida 14.2.17 and Frida 14.2.18 with frida-server 14.2.18

**Comment by RobLinux** [comment]
I have the very same problem with my OnePlus 8,Frida 14.2.18 & Android 10. And I need to hook functions at the start so definitely a problem :(_

**Comment by bojanisc** [comment]
I can confirm that I'm seeing the same issue on Samsung A40, with Android 11. Attaching to existing processes works OK, but spawning does not.

**Comment by BLuFeNiX** [comment]
I am also seeing this issue on a Galaxy Tab S6 Lite (rooted with Magisk), and Frida 15.0.0.

```
$ frida -U -l foo.js -f com.android.chrome
     ____
    / _  |   Frida 15.0.0 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Failed to spawn: unexpectedly timed out while waiting for app to launch
```

The chrome app itself **does** launch on the device, it is just never attached/detected.

**Comment by oleavr** [comment]
@2735106525 @chouex @RobLinux @bojanisc @BLuFeNiX Did you try disabling USAP? We don't yet support that.

**Comment by chouex** [comment]
confirm the master branch of frida-core worked, have to upgrade frida-tools and disable magisk hide first.

Frida 14.2.18 + magis hide => forever Spawning
Frida 15.0.6 + magis hide => Failed to spawn: unable to access PID **** (usap64) while preparing for app launch; try disabling Magisk Hide in case it is active
Frida 15.0.6=>
```frida -U -f com.tencent.mm
     ____
    / _  |   Frida 15.0.6 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Spawned `com.tencent.mm`. Use %resume to let the main thread start executing!
[KB2000::com.tencent.mm]-> %resume
[KB2000::com.tencent.mm]->
```

```
OnePlus8T:/ # getprop persist.device_config.runtime_native.usap_pool_enabled
*nothing*
OnePlus8T:/ #
```

**Comment by Karim0x1** [comment]
I had the same issue, disabling USAP worked.
`setprop persist.device_config.runtime_native.usap_pool_enabled false`

**Comment by oleavr** [comment]
We do support USAP as of latest Frida 15, but it hasn't been tested on a broad range of devices, so disabling it is a good solution if you run into issues.

**Comment by novitae** [comment]
Hey, I am getting this error, but on an iPhone 6 ... how can I fix it ? Thanks !

**Comment by SuperYogurt** [comment]
> Hey, I am getting this error, but on an iPhone 6 ... how can I fix it ? Thanks !

I have the same problem, have you solved it?

**Comment by Hunmuhe** [comment]
万分抱歉，我没使用过苹果系统



| |
hunmuhe
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 08/25/2022 17:59 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [frida/frida-core] Failed to spawn: unexpectedly timed out while waiting for app to launch (#376) |

Hey, I am getting this error, but on an iPhone 6 ... how can I fix it ? Thanks !

I have the same problem, have you solved it?

**Comment by RAISEN789** [comment]
hi, i have the same problem no one have a solution ? =(

**Comment by BLuFeNiX** [comment]
@RAISEN789 did you try the solution posted above?

**Comment by RAISEN789** [comment]
@BLuFeNiX yes the solution helped me, thanks

**Comment by OmkarKirpan** [comment]
> 

Thanks it worked

**Comment by durori** [comment]
This is what i do for samsung A50 and worked

```
adb shell
su
mount -o remount,rw '/'
chmod 777 /
adb shell "su -c setenforce 0"
setprop persist.device_config.runtime_native.usap_pool_enabled false
settings put system screen_off_timeout 100000000
exit
exit
```

now you can run frida-server
terminal 1 (use cmd for windows)
`adb shell "su -c /data/local/tmp/frida-serverarm64"`
terminal 2 (maybe powershell for windows)
`frida -U -f package.app -l script.js`

Good Luck

**Comment by whichname** [comment]
disable zygisk in magisk is worked

**Comment by gauravssnl** [comment]
I installed the frida-server-16.1.11-android-arm64 version first , it worked for a while and I tried to run the below command as per Frida doc : frida-trace -U -i open com.android.chrome , then my phone crashed and restarted.

**What work for me**

I have installed the frida-server-16.1.11-linux-arm64 ( **Linux version** ) and that works for me and phone is not crashing. You all can give this solution a try and let me know.

Note : my phone architecture is ARM64, please install the corresponding Linux version according to your phone architecture.

Let me know your results.

**Comment by spid3y777** [comment]
It really works : disable zygisk in magisk is worked as claimed by @whichname whichname co

**Comment by Icyrockton** [comment]
For users with OnePlus(一加) running ColorOS 15, please use the following command to terminate the zygote32 process. Otherwise, Frida will wait for the signal response from the zygote32 process (obviously timed out) instead of the expected zygote64 process.

```
setprop persist.sys.tango_zygote32.start 0
```

After this, `zygote_tango` will be stopped.

```
OP5CFBL1:/data/local/tmp # getprop | grep "zygote"
[init.svc.zygote]: [running]
[init.svc.zygote_ocomp]: [running]
[init.svc.zygote_tango]: [stopped]
[init.svc_debug_pid.zygote]: [26502]
[init.svc_debug_pid.zygote_ocomp]: [1611]
[init.svc_debug_pid.zygote_tango]: []
[persist.oplus.zygote_ocomp]: [true]
[persist.sys.system.abnormalboot]: [2025-01-15 07:44:49:zygote reboot by netd]
[persist.sys.tango_zygote32.start]: [0]
[ro.boottime.zygote]: [6197081507]
[ro.boottime.zygote_ocomp]: [6380248329]
[ro.boottime.zygote_tango]: [6382967496]
[ro.zygote]: [zygote64]
```

**Comment by fabiomoura71mar** [comment]
> For users with OnePlus(一加) running ColorOS 15, please use the following command to terminate the zygote32 process. Otherwise, Frida will wait for the signal response from the zygote32 process (obviously timed out) instead of the expected zygote64 process.
> 
> ```
> setprop persist.sys.tango_zygote32.start 0
> ```
> 
> After this, `zygote_tango` will be stopped.
> 
> ```
> OP5CFBL1:/data/local/tmp # getprop | grep "zygote"
> [init.svc.zygote]: [running]
> [init.svc.zygote_ocomp]: [running]
> [init.svc.zygote_tango]: [stopped]
> [init.svc_debug_pid.zygote]: [26502]
> [init.svc_debug_pid.zygote_ocomp]: [1611]
> [init.svc_debug_pid.zygote_tango]: []
> [persist.oplus.zygote_ocomp]: [true]
> [persist.sys.system.abnormalboot]: [2025-01-15 07:44:49:zygote reboot by netd]
> [persist.sys.tango_zygote32.start]: [0]
> [ro.boottime.zygote]: [6197081507]
> [ro.boottime.zygote_ocomp]: [6380248329]
> [ro.boottime.zygote_tango]: [6382967496]
> [ro.zygote]: [zygote64]
> ```

Thanks bro, its worked for me! I have OnePlus Ace 3 Pro on Android 15 Color OS!

**Comment by roda37** [comment]
While obvious, some may have not tried it, run this. This worked for me!

setprop persist.sys.tango_zygote64.start 1
