### ISSUE TITLE
Frida truncates output

### ISSUE THREAD

**Issue by azrinyi** [frida/frida-core#379]
I'm trying to print the output of a method parameter to the console but Frida truncates it as shown below:

```
[+] Class Name: NSData
[+] Param: {length = 32, bytes = 0x35e685a1 411a6058 52ec1045 ef7f16f1 ... a240a699 6edb306c }
[+] Return Value: 0x283da5560
```

The relevant section of the code looks like so:
```
console.log("[+] Param: " + ObjC.Object(args[2]).toString());
```
Shouldn't it print all 32 bytes to the console?

**Comment by oleavr** [comment]
No, this is Apple's `-[NSData description]` implementation that has this behavior. You should use the `NSData` API yourself to access the bytes.
