### ISSUE TITLE
Small tutorial on overwriting methods in Android

### ISSUE THREAD

**Issue by StefaanSeys** [frida/frida-core#38]
Hi,

I stumbled on Frida through this post
http://blog.mdsec.co.uk/2015/04/instrumenting-android-applications-with.html

Here they explain how you can create a new object of a particular class of an Android app:

    var LockManager = Dalvik.use("com.github.orangegangsters.lollipin.lib.managers.LockManager");
    var LockManagerInstance = LockManager.getInstance();

Would it be possible for you to write a small tutorial on how to overwrite a particular method of some class, i.e., hook a particular class method such that the overwritten method will be used whenever the App creates an object of that class, instead of the intended method that is in the APK code?

If I get it to work, I am very willing to write out a full tutorial to include on the frida.re site :-)

Thanks!

**Comment by Tyilo** [comment]
See http://www.frida.re/docs/javascript-api/#dalvik where there is an example for hooking the `onResume()` method on the `android.app.Activity` class:

```
Dalvik.perform(function () {
    var Activity = Dalvik.use("android.app.Activity");
    Activity.onResume.implementation = function () {
        send("onResume() got called! Let's call the original implementation");
        this.onResume();
    };
});
```

**Comment by MuntashirAkon** [comment]
How to override a method like this

```java
com.example.ExampleClass example = ...;
example.lambda$someMethod$0$com-example-ExampleClass();
```
`lambda$someMethod$0$com-example-ExampleClass` is not a valid Java method, but it's a valid (synthetic) method in Dex/Smali.
