### ISSUE TITLE
Substrate 0.9.7113 compatibility

### ISSUE THREAD

**Issue by mgrela** [frida/frida-core#382]
It looks like Frida is not working well with the newest Substrate when launching applications. The symptoms are the familiar error message:

```
# frida-server -v
{"type":"error","description":"Error: Unsupported version of Substrate; please file a bug","stack":"Error: Unsupported version of Substrate; please file a bug\n    at resolveFunction (/internal-agent.js:259)\n    at findSubstrateLauncher (/internal-agent.js:252)\n    at applyJailbreakQuirks (/internal-agent.js:152)\n    at <eval> (/internal-agent.js:50)","fileName":"/internal-agent.js","lineNumber":259,"columnNumber":1}
```

as well as the app starting but this fact not being noticed by frida on the host:

```
$ frida -U -f app
     ____
    / _  |   Frida 15.0.0 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
Failed to spawn: unexpectedly timed out while waiting for app to launch
$ 
```

A similar issue was solved for Substrate 0.9.7104 (https://github.com/frida/frida-core/issues/331) but the black magic used to reveal the proper hex strings was not revealed :(.

**Comment by oleavr** [comment]
Thanks for reporting! Yeah the process for figuring out what changed is tedious and requires static analysis of the closed-source Substrate code. There isn't much to it though – just dumping the in-memory Mach-O and looking at it with a static analysis tool. (It's also possible to find it embedded in some file on the filesystem – though I've forgotten exactly which.)

**Comment by oleavr** [comment]
Releasing 15.0.8 right now with this fix, and a fix for latest unc0ver. Cheers!
