### ISSUE TITLE
Frida cannot do open_channel to iOS device after 2018.9 with an old Windows iTunes usbmuxd (12.6.3)

### ISSUE THREAD

**Issue by NyaMisty** [frida/frida-core#384]
it will throw the following exception:
```
frida.NotSupportedError: unexpected result while trying to read pair record: 2
```

The reason is:
- Frida will always read the pair data when connect to lockdownd service
- Old Windows iTunes usbmuxd won't correctly handle the serial with hyphen, see https://github.com/libimobiledevice/libimobiledevice/issues/706
- newer usbmuxd is actually manually adding the hyphen: https://github.com/libimobiledevice/libimobiledevice/issues/706#issuecomment-427232740

So, we can add the hyphen in frida as well in the fruity-host-session to fix this issue. And even if I know the reason, I can't PR because I really can't write Vala, so please help me out if possible :(

**Comment by oleavr** [comment]
Thanks! Tried to reproduce this but wasn't able to get iTunes to successfully pair with my iPhone running iOS 14.7. It did however happily pair with an older iPad (with a long serial number), running 13.3.1. So I'm not sure if this fix actually helps. Let me know if you get a chance to try it though!

**Comment by NyaMisty** [comment]
Wow thanks for quick fix!
Is there any release schedule in a few days? If not I'll try to build it manually now~

**Comment by NyaMisty** [comment]
I've compiled frida myself. To test it you may have to install the latest iTunes 12.6.x (which is actually 12.6.5.3).
And I've tested the fix, it's fully working now with iPad Air 3 (14.2) and iTunes 12.6.5.3.
But I can't check whether the fix works with newest iTunes, maybe we should do some testing.

**Comment by oleavr** [comment]
The CI just finished chewing on 15.0.9. Thanks for testing!
