### ISSUE TITLE
working with reverse proxy

### ISSUE THREAD

**Issue by hellodword** [frida/frida-core#386]
Glad to know that frida 15 support websocket! It will make frida more powerful.

I'm tring to do remote debugging with [Cloudflare Tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/trycloudflare) (a simple reverse proxy).

```sh
# listen on android
# 1.2.3.4 is the IP of android
frida-server -l 0.0.0.0:8000 -D

# good
frida-ps -H 1.2.3.4:8000
# 1650  wificond                                       
# 2224  wpa_supplicant                                 
# 1636  zygote                                         
# 1635  zygote64  

# check the websocket server with curl
curl --http1.1 --include  --request GET \
  --url http://1.2.3.4:8000/ws \
  --header 'connection: Upgrade' \
  --header 'sec-websocket-key: dGhlIHNhbXBsZSBub25jZQ==' \
  --header 'sec-websocket-version: 13' \
  --header 'upgrade: websocket'
# HTTP/1.1 101 Switching Protocols
# Date: Fri, 30 Jul 2021 02:59:19 GMT
# Upgrade: websocket
# Connection: Upgrade
# Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
# Content-Length: 0

# https://github.com/cloudflare/cloudflared/releases/tag/2021.6.0
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/trycloudflare
cloudflared tunnel --url http://1.2.3.4:8000
# INF +------------------------------------------------------+
# INF |  Your free tunnel has started! Visit it:             |
# INF |            https://example.trycloudflare.com         |
# INF +------------------------------------------------------+

# HTTP
curl --http1.1 --include  --request GET \
  --url http://example.trycloudflare.com/ws \
  --header 'connection: Upgrade' \
  --header 'sec-websocket-key: dGhlIHNhbXBsZSBub25jZQ==' \
  --header 'sec-websocket-version: 13' \
  --header 'upgrade: websocket'
# HTTP/1.1 101 Switching Protocols
# Date: Fri, 30 Jul 2021 02:59:19 GMT
# Upgrade: websocket
# Connection: Upgrade
# Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
# Content-Length: 0
# CF-Cache-Status: DYNAMIC
# Server: cloudflare

# HTTPS
curl --http1.1 --include  --request GET \
  --url https://example.trycloudflare.com/ws \
  --header 'connection: Upgrade' \
  --header 'sec-websocket-key: dGhlIHNhbXBsZSBub25jZQ==' \
  --header 'sec-websocket-version: 13' \
  --header 'upgrade: websocket'
# HTTP/1.1 101 Switching Protocols
# Date: Fri, 30 Jul 2021 02:59:19 GMT
# Upgrade: websocket
# Connection: Upgrade
# Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
# Content-Length: 0
# CF-Cache-Status: DYNAMIC
# Server: cloudflare

frida-ps -H example.trycloudflare.com
# Failed to enumerate processes: unable to connect to remote frida-server: Could not connect to example.trycloudflare.com: Connection timed out

frida-ps -H example.trycloudflare.com:80
# Failed to enumerate processes: bad Request

frida-ps -H example.trycloudflare.com:443
# Failed to enumerate processes: bad Request
```

---

```vala
string uri = "%s://server/ws".printf ((transport == TLS) ? "wss" : "ws");
request.append_printf ("GET %s HTTP/1.1\r\n", uri);
var msg = new Soup.Message ("GET", uri);
```

I find the host [here](https://github.com/frida/frida-core/blob/cb078a18e562266b572ca4be05412cc23689507e/lib/base/socket.vala#L96-L98) is `server`, is this the reason?

[[MDN] Client handshake request](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#client_handshake_request)
```
GET /chat HTTP/1.1
Host: example.com:8000
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
Sec-WebSocket-Version: 13

```

---

BTW, if this can be supported, I think the `host` could be a url, so frida-tools can know the scheme (ws or wss) without other command line arguments. We can add tls, cdn, or authentication supports with other programs or services. It will make frida more flexible.

**Comment by oleavr** [comment]
This is now working in Frida 15.0.13, just released 🎉  Thanks a lot for your help in getting to the bottom of this! 🙌

**Comment by hellodword** [comment]
> This is now working in Frida 15.0.13, just released  Thanks a lot for your help in getting to the bottom of this!

Great!

But 15.0.13 is not working for me, any steps to show it?

```sh
frida-server --version
# 15.0.13

frida-ps --version
# 15.0.13
```

I added `--loglevel debug --transport-loglevel debug` to cloudflared, it will show the request logs.

I could see the request logs when using `curl`, but no logs when using `frida-ps -H example.trycloudflare.com`

```sh
curl --http1.1 --include  --request GET \
  --url http://example.trycloudflare.com/ws \
  --header 'connection: Upgrade' \
  --header 'sec-websocket-key: dGhlIHNhbXBsZSBub25jZQ==' \
  --header 'sec-websocket-version: 13' \
  --header 'upgrade: websocket'
# HTTP/1.1 101 Switching Protocols
# Date: Fri, 30 Jul 2021 02:59:19 GMT
# Upgrade: websocket
# Connection: Upgrade
# Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
# Content-Length: 0
# CF-Cache-Status: DYNAMIC
# Server: cloudflare
```

**Comment by hellodword** [comment]
And one another question is how to target wss without `--certificate` in the future, the `host` cannot contain scheme info.

```sh
# HTTPS
curl --http1.1 --include  --request GET \
  --url https://example.trycloudflare.com/ws \
  --header 'connection: Upgrade' \
  --header 'sec-websocket-key: dGhlIHNhbXBsZSBub25jZQ==' \
  --header 'sec-websocket-version: 13' \
  --header 'upgrade: websocket'
# HTTP/1.1 101 Switching Protocols
# Date: Fri, 30 Jul 2021 02:59:19 GMT
# Upgrade: websocket
# Connection: Upgrade
# Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
# Content-Length: 0
# CF-Cache-Status: DYNAMIC
# Server: cloudflare
```

**Comment by hellodword** [comment]
BTW, I'm thinking about that isolating the clients (`frida-tools` or `frida-python` for example) from the `frida-core` will be better. 

The `frida-server` can focus on the interface designing and protocol docs of how to interoperate or communicate with it.

So anyone can implement a client without reading vala, that's amazing I think.

 (I love the future of frida which is shown by [`web_client`](https://github.com/frida/frida-python/tree/bbdcdfaca821276361399775bd81599710ec0625/examples/web_client):raised_hands:)

**Comment by oleavr** [comment]
> I could see the request logs when using curl, but no logs when using frida-ps -H example.trycloudflare.com

The default port is 27042, so to use port 80 it must be specified like this: `frida-ps -H example.trycloudflare.com:80`. This may seem counterintuitive but is to match the default port used by our servers.

> And one another question is how to target wss without --certificate in the future, the host cannot contain scheme info.

The `--certificate` must be specified to enable TLS. We don't currently make use of system-wide root certs, and don't inline a repo in Frida, so we require the user to specify a CA cert/chain here. The server-presented cert must match or be derived from it.

> BTW, I'm thinking about that isolating the clients (frida-tools or frida-python for example) from the frida-core will be better.

Not sure I'm following. They're more than just clients though, they also have the local backend and meta-backends that know how to talk to usbmuxd/adb in order to support jailed/non-rooted devices without a frida-server.

> (I love the future of frida which is shown by web_client🙌)

Glad to hear! 🙌

**Comment by hellodword** [comment]
> The default port is 27042, so to use port 80 it must be specified like this: frida-ps -H example.trycloudflare.com:80. This may seem counterintuitive but is to match the default port used by our servers.

Great! HTTP works.

> The --certificate must be specified to enable TLS. We don't currently make use of system-wide root certs, and don't inline a repo in Frida, so we require the user to specify a CA cert/chain here. The server-presented cert must match or be derived from it.

I thought the TLS can be client-side, because in this case, server will only receive requests without TLS. Okay, I will try to learn that in `frida-core`.
