### ISSUE TITLE
Why attach() does not support 'gadget' option like spawn()

### ISSUE THREAD

**Issue by douniwan5788** [frida/frida-core#411]
spawn():
https://github.com/frida/frida-core/blob/0669d6bbd1db1889a8b42051d1b755f8655d8512/src/fruity/fruity-host-session.vala#L1048-L1056

attach():
https://github.com/frida/frida-core/blob/0669d6bbd1db1889a8b42051d1b755f8655d8512/src/fruity/fruity-host-session.vala#L1186-L1188

Is there any way to specify the gadget path for attach() ?

**Comment by oleavr** [comment]
It doesn't support it because it's not yet implemented. (PRs welcome!)

**Comment by lilili87222** [comment]
can you implement some api to set gadget.dylib path ?
