### ISSUE TITLE
`device.resume` is not working on iOS

### ISSUE THREAD

**Issue by ChiChou** [frida/frida-core#462]
I got a lot of issues regarding weird crashes. After a while I finally realized the root cause. When an app is spawned by frida, it never gets resumed, causing SpringBoard to kill it (a.k.a. 0x8badf00d).

Reproduce:

```js
const frida = require('frida')

async function main() {
    const dev = await frida.getUsbDevice();
    const pid = await dev.spawn('com.google.chrome.ios');
    await dev.resume(pid);
}

main()
```

Or

```py
import frida


dev = frida.get_usb_device()
pid = dev.spawn('com.google.chrome.ios')

import time
time.sleep(1)

dev.resume(pid)
```

However `frida-tools -f` works perfectly on iOS.

I checked the source and it's no different than the python test case above, which makes no sense.

**Comment by ChiChou** [comment]
I realized that I need to attach the target to make it really resume...

**Comment by oleavr** [comment]
Thanks for reporting! That is still a bug. It is not a requirement to `attach()` before `resume()`. So we should figure out what's causing this.

**Comment by bigbangvn** [comment]
Hi @ChiChou Can I know what is the solution for this issue?
I'm using CLI, and getting similar issue:

```
frida -U -f "<bundle id>"
```

And process doesn't resume, already try comands listed here:

```
help
Available commands: 
  %resume(0) - resume execution of the spawned process
  %load(1) - Load an additional script and reload the current REPL state
  %reload(0) - reload (i.e. rerun) the script that was given as an argument to the REPL
  %unload(0) - no description
  %autoperform(1) - receive on/off as first and only argument, when switched on will wrap any REPL code with Java.performNow()
  %autoreload(1) - disable or enable auto reloading of script files
  %exec(1) - execute the given file path in the context of the currently loaded scripts
  %time(1+) - measure the execution time of the given expression and print it to the screen
  %help(0) - print a list of available REPL commands

```

**Comment by ChiChou** [comment]
@bigbangvn by default you don't need to resume. Please check your jailbreak env

**Comment by bigbangvn** [comment]
@ChiChou Not sure why it doesn't resume. My workaround now is triggering "frida -U -n "<App name>" on another tab to resume it
