### ISSUE TITLE
Frida gadget on Windows: autonomous script interaction mode - instrumented process remains alive in a sort of "zombie" state after quitting it

### ISSUE THREAD

**Issue by Palacee-hun** [frida/frida-core#468]
I have written an instrumentation with Frida for an app. It turned out to be very useful and I have been using it a lot, so I thought I'd try to package it together with the app with the help of the autonomous script mode of Frida gadget.

So I copied my instrumentation js script to the directory of the app and I also copied frida gadget dll there renamed as helper.dll. I also created helper.config, setting interactions to "script" and on_change to "reload" in it and of course the path of my script.

Then as a first try I injected frida gadget dll into the running app with two tools: inject.exe from Comrade's PETOOLS and procwin.exe written by Japheth. My instrumentation worked flawlessly with both tools and the app quit all right. Then I took the plunge and patched the app executable with patch.exe also from Comrade's PETOOLS so that it would load frida gadget dll first upon starting before doing anything else. This was also successful: the instrumented app did what it was supposed to do and quit normally.

After all this I was surprised to still see instances of the instrumented process listed in my process explorer, although they had quit normally, their windows had been closed and I saw no visible traces of them running.

So I investigated those "zombie" processes and I saw that they unloaded some of their dependent dlls, but not all. And helper.dll (frida gadget dll) was still loaded in all cases together with its dependency dlls. It was always possible to kill the zombie processes easily. So somehow frida gadget dll didn't detach from the process when it quit.

I have tried all this with rpc.exports and init/dispose in my js script and also without them: this made absolutely no difference and the results were the exact same. I experimented with other processes and instrumentations and this zombie process thing was 100 % reproducible when doing it with frida gadget dll, but it has never eve happened when using the python frida toolset. I tried to temporarily disable my antivirus too, but it also did not matter.

My system is Windows 7 Ultimate 32-bit.

**Comment by oleavr** [comment]
Thanks for reporting!

Sorry it took me three years to notice/actually think about this issue. I'm clearly stretched too thin and struggling to keep on top of things. I skim through new issues as they come in, but sometimes I'm interrupted in the middle and don't realize until much later.

This turned out to be an easy one that didn't require reading code or debugging, so I'm a bit embarrassed that we've had this silly bug sitting there for so long. Not just that, but it was right there in Gadget's own code, which is only ~2100 LOC of Vala and ~300 LOC of C/Objective-C (it currently lives [here](https://github.com/frida/frida-core/tree/856752e341107a71557aa88128e80191a20ca798/lib/gadget). I had screwed up in `DllMain` when handling `DLL_PROCESS_DETACH`. 🤦

**Comment by cesaryuan** [comment]
> Thanks for reporting!
> 
> Sorry it took me three years to notice/actually think about this issue. I'm clearly stretched too thin and struggling to keep on top of things. I skim through new issues as they come in, but sometimes I'm interrupted in the middle and don't realize until much later.

Thank you so much for your fix, it's really great🥰. One more thing I want to know, when is the next release, I hope to use it as soon as possible haha. Because I found that my locally built gadget.dll does not work properly in Script mode, so I can only rely on the Release build.😂

**Comment by oleavr** [comment]
> Thank you so much for your fix, it's really greatsmiling_face_with_three_hearts.

:raised_hands:

> One more thing I want to know, when is the next release

One of the next days, just waiting for some other fixes to land.

> So should I commit the `chacater set` changes to the frida?

Ooh, thanks, nice catch! It would be great to add them to `releng/frida.props` instead, so it applies to all projects.
