### ISSUE TITLE
get_frontmost_application inconsistent between ios and android

### ISSUE THREAD

**Issue by juliangruber** [frida/frida-core#48]
On android there's always a frontmost application returned, like the google search box, whereas on ios there isn't (could be springboard).

Is this intentional?

**Comment by oleavr** [comment]
Good point! There is a theoretical chance that it will also return `null` on Android (on a stripped down system), but I'm a bit uncertain if having a fallback to the "desktop" would make sense. Running Frida on a headless Linux system without X/Wayland I guess we could fallback to pid 1 (`init` / `systemd`). OTOH maybe we want to go in the other direction, and have the Android backend be a bit stricter so it only considers something the foreground app if it's actually an app and not a launcher widget. What do you think?

**Comment by juliangruber** [comment]
My vote is for making android more strict, since it's surprising that a widget is considered to be the frontmost application.

**Comment by oleavr** [comment]
Agreed, let's go for that! :+1:
