### ISSUE TITLE
`inject_library_blob` feature regression in `16.0.12`

### ISSUE THREAD

**Issue by romainthomas** [frida/frida-core#480]
Starting from Frida 16.0.12, `device.inject_library_blob` seems no longer working.

With Frida 16.0.11, [examples/inject_library/inject_blob.py](https://github.com/frida/frida-python/blob/main/examples/inject_library/inject_blob.py) is working while with Frida 16.0.12, we get the following error:

```
Console:
frida.TransportError: agent connection closed unexpectedly

adb logcat:
type=1400 audit(0.0:213): avc: denied { write } for path=2F6D656D66643A626C6F62352E736F202864656C6574656429 dev="tmpfs" ino=8564 scontext=u:r:untrusted_app:s0:c10,c257,c512,c768 tcontext=u:object_r:tmpfs:s0 tclass=file permissive=0 app=****************************
```

--- 

Environment:
**Device**: Pixel 7
**Android Version**: 13 (TQ1A.230205.002)

**Comment by oleavr** [comment]
Thanks!! (And sorry for the delay, saw this way too late! :sweat_smile:)
