### ISSUE TITLE
frida ignores callbacks on windows system

### ISSUE THREAD

**Issue by K-S-V** [frida/frida-core#51]
Hi, first huge thanks for your effort in creating this toolset. 

I was trying to get frida-trace working on WinXP SP3 (x86). I am using the latest version available at the moment (6.0.1).  I am trying to hook the PaintMenuBar function of calc.exe or notepad.exe. cmd output shows that it successfully injects the frida-agent dll and started tracing our target function. I have verified with **Ollydbg** that it successfully replaces the target function's first bytes with jump to frida-agent dll. whenever we activate the target process window PaintMenuBar function is called and it successfully executes frida-agent code. now the problem is that nothing is being logged in the cmd window. I haven't modified auto generated handlers in anyway. I checked with **TcpView** tool that after the initial communication, injected frida-agent is not sending any messages back to python client whenever our target function is being invoked. I tried to hook several other functions both in calc.exe and notepad.exe but it seems to ignore all of them. I have already tried disabling my security software. any thoughts on what could be the problem and how can i fix it?

**Comment by oleavr** [comment]
Hi,

Thanks for reporting! You won't see anything in **TcpView** because Frida uses a named pipe to communicate between the python process (frida-trace) and the injected agent in the target process. This sounds like a bug in frida-python where maybe the logging broke. Did you try hooking other functions?

Cheers!

**Comment by K-S-V** [comment]
I have looked further into it. TcpView showed communication to port 5037 when frida-trace tried to communicate with adb and to port 27015 for discovering iPhone etc. so lack of any further communication over those ports isn't related to current problem. I have tested with several other functions both in calc.exe as well as notepad.exe but the result is same. i even tried **frida-node** bindings with your node example but result is same. communication channel works fine. hooked function is being called and it also jumps to frida-agent dll but specified callbacks never get fired for intercepted function. here is the minimal test script i am using.

**test.py**
```python
import codecs
import frida
import sys

def on_message(message, data):
    if message['type'] == 'send':
        print(message['payload'])
    elif message['type'] == 'error':
        print(message['stack'])

session = frida.attach('calc.exe')
with codecs.open('./agent.js', 'r', 'utf-8') as f:
    source = f.read()
script = session.create_script(source)
script.on('message', on_message)
script.load()
script.post_message("communication channel test")
script.post_message({
    u'type': u'attach', u'payload': {
        u'_module': u'user32.dll', u'_function': 'PaintMenuBar'
    }
})
sys.stdin.read()
```

**agent.js**
```javascript
 function onMessage(message) {
 	send("received " + message);
 	recv(onMessage);
 }

 function onAttach(message) {
 	var module = message.payload._module;
 	var func = message.payload._function;
 	var hndl = Module.findExportByName(module, func);
 	send("attaching to function " + func + " found at " + hndl + " in module " + module);
 	Interceptor.attach(hndl, {
 		onEnter: function(args) {
 			send("callback onEnter executed");
 		},
 		onLeave: function(retval) {
 			send(
 				"callback onLeave executed");
 		}
 	});
 }

 recv(onMessage);
 recv('attach', onAttach);
```

can you spot something wrong with above scripts?

**Comment by K-S-V** [comment]
I would like to provide an update on the issue. This bug doesn't affect all target binaries. I was successfully able to use following scripts to trace target functions in Skype.exe and Excel.exe while the same scripts fail in case of calc.exe or notepad.exe despite the fact that target functions are being hooked correctly and being called by the target process.

**Hello.py**
``` python
import codecs
import frida
import sys

def on_message(message, data):
    print message

session = frida.attach(sys.argv[1])
with codecs.open('./Hello.js', 'r', 'utf-8') as f:
    source = f.read()
script = session.create_script(source)
script.on('message', on_message)
script.load()
sys.stdin.read()
```

**Hello.js**
``` javascript
var hndl;
hndl = Module.findExportByName("user32.dll", "PeekMessageA");
Interceptor.attach(hndl, {
	onEnter: function(args) {
		send("PeekMessageA callback executed");
	}
});
hndl = Module.findExportByName("user32.dll", "PeekMessageW");
Interceptor.attach(hndl, {
	onEnter: function(args) {
		send("PeekMessageW callback executed");
	}
});
hndl = Module.findExportByName("user32.dll", "GetMessageA");
Interceptor.attach(hndl, {
	onEnter: function(args) {
		send("GetMessageA callback executed");
	}
});
hndl = Module.findExportByName("user32.dll", "GetMessageW");
Interceptor.attach(hndl, {
	onEnter: function(args) {
		send("GetMessageW callback executed");
	}
});
```

**Comment by riverar** [comment]
Have verified PaintMenuBar is called indirectly via the uxtheme theming hook.

```
00 USER32!PaintMenuBar
01 uxtheme!OnDwpNcActivate
02 uxtheme!_ThemeDefWindowProc
03 uxtheme!ThemeDefWindowProcW
04 USER32!ScreenToClient
05 calc!CalcWndProc
```

I thought the uxtheme hook was potentially squashing the Interceptor but doesn't seem to be the case. How curious.

Looking at this now.

**Comment by riverar** [comment]
Was chatting with @oleavr, this issue appears on binaries, like calc.exe, with PE stack reserve size set to < 1MB. A workaround would be to ```editbin /stack:1048576 calc.exe``` to ensure each thread gets at least 1MB of stack space for frida to do its thing.

**Comment by K-S-V** [comment]
Thanks to both of you for looking into this and providing a workaround for the issue. None of those applications (calc.exe, notepad.exe) was my main target. I was just using them to assess the capabilities of frida but unfortunately I hit this particular edge case during my initial testing.

**Comment by oleavr** [comment]
@K-S-V Bad luck, but a very nice find. :) I think we have two possible solutions to this:
- Switch to our own per-thread stack when we invoke the callback that ends up calling into V8. This can easily be done only for threads with little stack space, as we already have some per-thread data that we initialize only once, and that's a good time to make that assessment. The side-stack part of this has already been implemented once by @s1341, as he ran into this issue when porting Frida to QNX, where threads are created with a tiny stack by default. So this solution would be about making @s1341's feature more generic, and only applied when needed.
- Let users easily select that they want to use the brand new [duktape](http://duktape.org/)-based runtime that @s1341 recently contributed. This one allows Frida to run on resource-constrained embedded devices (the duktape engine has a minimum requirement of 256kB flash and 96kB system RAM). This runtime is so small that we could even include it alongside V8 and it would only add a few hundred kilobytes of binary footprint.

**Comment by oleavr** [comment]
You can now work around this problem by using `--disable-jit` (CLI tools) and `session.disable_jit()` (API), which will use the Duktape-based runtime.

**Comment by K-S-V** [comment]
@oleavr Thanks for the fix. it works as expected after using the suggested switch.
