### ISSUE TITLE
Frida 6.0.8 cannot spawn or atach on Win7 x64 

### ISSUE THREAD

**Issue by 0xABD** [frida/frida-core#54]
I have encountered an issue with Frida 6.0.8 on fully patched Win 7 SP1 x64 while trying to instrument any local process.
The spawn or attach command will fail with the same error:
```
C:\>frida -f %WINDIR%\system32\calc.exe
    _____
   (_____)
    |   |    Frida 6.0.8 - A world-class dynamic instrumentation framework
    |   |
    |`-'|    Commands:
    |   |        help      -> Displays the help system
    |   |        object?   -> Display information about 'object'
    |   |        exit/quit -> Exit
    |   |
    |   |    More info at http://www.frida.re/docs/home/
    `._.'

Failed to attach: error opening named pipe (ConvertStringSecurityDescriptorToSecurityDescriptor returned 0x00000539)
```
As per MSDN:
0x00000539 = ERROR_INVALID_SID [1337 (0x539) The security ID structure is invalid.]

**Comment by P4l1ndr0m** [comment]
Same issue here with windows 8.1 64bits. Frida worked flawlessly two days ago, today I get the following error.
![frida_fail_to_attach](https://cloud.githubusercontent.com/assets/4301170/12053119/b5e84e6a-af0d-11e5-8b9d-cf9be92898ff.PNG)

**Comment by oleavr** [comment]
Thanks for the reports! This seems to be a regression caused by this recent improvement:
https://github.com/frida/frida-core/commit/a95a5e6d88d205ccd8f7faadbafdc929c044bb3f

@riverar What do you think would be the best way to solve this?

**Comment by riverar** [comment]
My bad, AppContainer didn't exist in Windows 7, so makes sense it can't recognize the related sddl bits. I'll probably bring in the OS version helpers to help here. PR soon.

This will likely affect all Windows versions earlier than Windows 8.

**Comment by oleavr** [comment]
@riverar Awesome! Let's get a new release out as soon as it lands.

**Comment by oleavr** [comment]
@riverar I just pushed a hot-fix release adding a temporary kludge where we fallback to the old logic, so let's do another release as soon as your PR is ready (I think we can release as often as once per day without making PyPI or npm angry at us :-) ).
