### ISSUE TITLE
ERROR: Could not execute Vala compiler in Android x64

### ISSUE THREAD

**Issue by KILLERALPHA** [frida/frida-core#541]
I tried to build frida in Androidx64 Termux and getting error 
defined below 

    ~ $ cd frida-core
    ~/frida-core $ make
    Downloading toolchain 20240729...
    Extracting toolchain...
    The Meson build system
    Version: 1.4.99
    Source dir: /data/data/com.termux/files/home/frida-core
    Build dir: /data/data/com.termux/files/home/frida-core/build
    Build type: native build
    Program python3 found: YES (/data/data/com.termux/files/usr/bin/python3)
    Project name: frida-core
    Project version: 16.4.8
    C compiler for the host machine: /data/data/com.termux/files/usr/bin/cc -march=armv8-a (clang 18.1.7 "clang version 18.1.7")
    C linker for the host machine: /data/data/com.termux/files/usr/bin/cc -march=armv8-a ld.lld 18.1.7
    C++ compiler for the host machine: /data/data/com.termux/files/usr/bin/c++ -march=armv8-a (clang 18.1.7 "clang version 18.1.7")
    C++ linker for the host machine: /data/data/com.termux/files/usr/bin/c++ -march=armv8-a ld.lld 18.1.7

    meson.build:1:0: ERROR: Could not execute Vala compiler: /data/data/com.termux/files/home/frida-core/deps/toolchain-linux-arm64/bin/valac-0.58 --vapidir=/data/data/com.termux/files/home/frida-core/deps/toolchain-linux-arm64/share/vala-0.58/vapi '--pkg-config=/data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/home/frida-core/build/frida-pkg-config.py'

    A full log can be found at /data/data/com.termux/files/home/frida-core/build/meson-logs/meson-log.txt
    Command '['/data/data/com.termux/files/usr/bin/python3', '/data/data/com.termux/files/home/frida-core/releng/meson/meson.py', 'setup', '-Dprefix=/usr/local', '-Ddefault_library=static', '-Doptimization=s', '-Db_ndebug=true', '-Dstrip=true', '--native-file=/data/data/com.termux/files/home/frida-core/build/frida-linux-arm64.txt', PosixPath('/data/data/com.termux/files/home/frida-core/build')]' returned non-zero exit status 1.
    make: *** [Makefile:4: all] Error 1
    
    
i also looked at this issues seems same like me GitHub.com/frida/frida/issues/2926
but getting same error, here is the log2 

    ~/frida-core $ ./configure --without-prebuilds=toolchain
    Building Vala compiler...
    Downloading SDK 20240729 for linux-arm64...
    Extracting SDK...
    The Meson build system
    Version: 1.4.99
    Source dir: /data/data/com.termux/files/home/frida-core
    Build dir: /data/data/com.termux/files/home/frida-core/build
    Build type: native build
    Program python3 found: YES (/data/data/com.termux/files/usr/bin/python3)
    Project name: frida-core
    Project version: 16.4.8
    C compiler for the host machine: /data/data/com.termux/files/usr/bin/cc -march=armv8-a (clang 18.1.7 "clang version 18.1.7")
    C linker for the host machine: /data/data/com.termux/files/usr/bin/cc -march=armv8-a ld.lld 18.1.7
    C++ compiler for the host machine: /data/data/com.termux/files/usr/bin/c++ -march=armv8-a (clang 18.1.7 "clang version 18.1.7")
    C++ linker for the host machine: /data/data/com.termux/files/usr/bin/c++ -march=armv8-a ld.lld 18.1.7

    meson.build:1:0: ERROR: Unknown compiler: /data/data/com.termux/files/home/frida-core/deps/toolchain-linux-arm64/bin/valac-0.58 --vapidir=/data/data/com.termux/files/home/frida-core/deps/toolchain-linux-arm64/share/vala-0.58/vapi '--pkg-config=/data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/home/frida-core/build/frida-pkg-config.py'

    A full log can be found at /data/data/com.termux/files/home/frida-core/build/meson-logs/meson-log.txt
    Command '['/data/data/com.termux/files/usr/bin/python3', '/data/data/com.termux/files/home/frida-core/releng/meson/meson.py', 'setup', '-Dprefix=/usr/local', '-Ddefault_library=static', '-Doptimization=s', '-Db_ndebug=true', '-Dstrip=true', '--native-file=/data/data/com.termux/files/home/frida-core/build/frida-linux-arm64.txt', PosixPath('/data/data/com.termux/files/home/frida-core/build')]' returned non-zero exit status 1.
    
my device Android 10, x64
HELP!!

**Comment by zozayashir** [comment]
ANY SOLUTIOn?
