### ISSUE TITLE
Injection fails on Windows 10 Metro/Modern apps

### ISSUE THREAD

**Issue by brandon15811** [frida/frida-core#67]
Metro apps on Windows 10 have more security than regular programs, so the dll injection fails
A possible fix would be to put the dll in `system32` (http://blog.nektra.com/main/2013/02/25/injecting-a-dll-in-modernui-metro-app-win8/ )

\cc @riverar

**Comment by riverar** [comment]
I specifically added code to support this. Can you provide more details about which app? And the version of frida you're using?

**Comment by brandon15811** [comment]
`frida-trace` reports 6.2.1. I tested it against the calculator (which is now a metro app), Xbox app, and Minecraft Windows 10 Edition, and they all crashed. For calculator, I used the command like `frida-trace Calculator.exe` to test

**Comment by riverar** [comment]
What build of Windows 10?

**Comment by riverar** [comment]
Thanks @brandon15811 for the live feedback in the IRC channel and reporting the issue!

**Comment by brandon15811** [comment]
No problem!
