### ISSUE TITLE
Error binding to address: Address already in use

### ISSUE THREAD

**Issue by BJJLeon** [frida/frida-core#69]
I'm getting the following error when I try to run it on my Android Phone. Works great on  iOS.

C:\WINDOWS\system32>adb shell "/data/local/tmp/frida-server &"
Unable to load SELinux policy from the kernel: Failed to open file '/sys/fs/selinux/policy': Permission denied
Unable to start server: Error binding to address: Address already in use

**Comment by DonTim** [comment]
I set SELinux to permissive and it worked but now I'm getting the following error
C:\WINDOWS\system32>frida-ps -U
Waiting for USB device to appear...
Failed to enumerate processes: unable to connect to remote frida-server: closed

**Comment by oleavr** [comment]
Are you running frida-server as root? You shouldn't have to set SELinux to permissive.

**Comment by DonTim** [comment]
Yes it was my fault. I got it working now. 

I ran into another issue. When I do the following 

`jscode = """
Dalvik.perform(function () {
    var myClass = Dalvik.use("com.myApp.MyClass");
	var MyClassInstance = myClass.$new();
	MyClassInstance.b();
	var result = MyClassInstance.a("{\"app\"}", 1, 145510);
    send(result);
});
"""`

I receive the following error 
Traceback (most recent call last):
  File "new.py", line 18, in <module>
    script = p.create_script(jscode)
  File "C:\Users\Timo\AppData\Local\Programs\Python\Python35-32\lib\site-packages\frida\core.py", line 188, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
frida.TransportError: gDBus.Error:re.frida.Error.InvalidArgument: Script(line 6): SyntaxError: missing ) after argument list

It works fine when I pass a normal string to a() but when I pass a string with escape characters such as "{\"app\"}" it wont accept it. Any suggestions?

**Comment by oleavr** [comment]
Cool! That sounds like a Python question, but I'd recommend rather just loading the JS from a file and avoid the need to escape things.

**Comment by DonTim** [comment]
Alright I will try that thanks.

**Comment by madhuCNKony** [comment]
adb push frida-server-12.0.8-android-arm /data/local/tmp/
adb shell "chmod 755 /data/local/tmp/frida-server-12.0.8-android-arm"
adb shell "/data/local/tmp/frida-server-12.0.8-android-arm &"

Getting below error (on my windows 10)
Unable to load SELinux policy from the kernel: Failed to open file ΓÇ£/sys/fs/selinux/policyΓÇ¥: Permission denied

**Comment by oleavr** [comment]
@madhuCNKony You have to run `frida-server` as root.

**Comment by Jahanzaeb** [comment]
@oleavr we are facing same issue as mentioned above we are runing frida server as root on [Samsung galaxy A710FD) but facing same error :
"Unable to load SELinux policy from the kernel: Failed to open file ΓÇ£/sys/fs/selinux/policyΓÇ¥: Permission denied"
Please guide me how I can fix this issue?

**Comment by ArIjIT8372** [comment]
> 
> 
> @oleavr we are facing same issue as mentioned above we are runing frida server as root on [Samsung galaxy A710FD) but facing same error :
> "Unable to load SELinux policy from the kernel: Failed to open file ΓÇ£/sys/fs/selinux/policyΓÇ¥: Permission denied"
> Please guide me how I can fix this issue?

check dis link 

https://github.com/frida/frida/issues/597#issuecomment-713652331 check dis
https://www.gitmemory.com/issue/frida/frida/1619/769144649

**Comment by shakitavi** [comment]
hello been trying to get frida to run for a few days now, (google pixel2XL, taimen, running as root) getting this error when I run the last step of the tutorial and unable to run frida-ps, 

data/local/tmp/frida-server &                                              <
[1] 9024
taimen:/data/local/tmp # Unable to start: Error binding to address 127.0.0.1:27042: Address already in use

I've found a few other resources telling me that frida will let you change ports once the server is installed, but can't even seem to get that far. Any help is appreciated!

**Comment by shakitavi** [comment]
in addition, when I exit root to get back to my regular shell I get this:

exit       
[1] + Done (5)             /data/local/tmp/frida-server
