### ISSUE TITLE
How to print NSString / Dictionary ?

### ISSUE THREAD

**Issue by cades** [frida/frida-core#7]
Hey frida team,

I have great fun time playing with frida, thank you guys!
I want to print the parameter, which have a string stored in NSString/NSDictionary, etc.
I tried Memory.readUtf8String and ObjC.selectorAsString, both give me "�sw�".

In objective-C, a simple `NSLog(@”%@”, str)` does what I want. Is there anything can achieve that?

**Comment by dnet** [comment]
To anyone arriving here from web search results; the syntax has changed since:

    var str = ObjC.Object(ptr("0x1234"));

**Comment by ChiChou** [comment]
@cades In ObjectiveC you can get the raw utf-8 encoded string from an NSString object with `UTF8String`, which can be printed directly in REPL.

e.g.

```javascript
ObjC.classes.NSProcessInfo.processInfo().processName().UTF8String()
```

**Comment by dpnishant** [comment]
It seems that the methods/API has changed quite a bit since this question was last answered. I'm not sure how do I iterate through a NSDictionary. I can print the keys and values separately using  

```
var arg0 = new ObjC.Object(args[0]);
console.log(arg0.allKeys());
console.log(arg0.allValues());

```
but how do I for a for..each loop through this dictionary something like this: http://stackoverflow.com/questions/1062110/how-to-use-nsenumerator-with-nsmutabledictionary

**Comment by 3xp10it** [comment]
@oleavr I want to print `NSTableColumn` type value,how can I make it ?
I hook a function and try to print args[3],first I get it's type with :
`console.log('Type of args[3] -> ' + new ObjC.Object(args[3]).$className)`
it returns `NSTableColumn`,then I try to print it with:
```
    //console.log('Type of args[3] -> ' + new ObjC.Object(args[3]).$className)
    var NSTableColumn = ObjC.use("NSTableColumn");
    var str = ObjC.cast(args[3], NSTableColumn);
    console.log(str)
```
but it doesn't work:(
Can you help me?
