### ISSUE TITLE
Support for enumerating loaded classes on Android 5.1.1

### ISSUE THREAD

**Issue by dpnishant** [frida/frida-core#75]
Running the following on Android 5.1.1 on Nexus 5

`var classes = Java.enumerateLoadedClassesSync();`

throws the following error.

```
Error: Enumerating loaded classes is only supported on Dalvik for now
    at _enumerateLoadedClasses (gumjs-java.js:172:23)
```

**Comment by oleavr** [comment]
Let's keep tracking this at frida/frida-java#17.
