### ISSUE TITLE
iOS: Access violation when using args in Interceptor.attach onEnter

### ISSUE THREAD

**Issue by StefaanSeys** [frida/frida-core#76]
Hi,

I am using **frida 7.1.4** to modify the behavior of an App on iOS and ran in a problem that I do not understand:

This is what I do:
- use Module.enumerateExports to get the address of the method that I want to hook
- use Interceptor.attach to hook that address and just print out the args[2](should be the argument passsed to the method). But this gives an Access violation

The method that I am hooking (stringForKey) gets a String as parameter. And I am sure that the method gets called by the code twice with two different String constants as parameter.

I have two questions:
**1. Why is it giving this access violation (is on jailbroken iOS version 8.1)
2. Why is the Module.enumerateExports finding two matches, while there is only one method in the code that matches the "stringForKey" (see output for details)?**

Code snippet of my hook:

``` javascript
     Module.enumerateExports('<TARGET_APP>', {
        onMatch: function(match) {
            if (match.name.indexOf('stringForKey') > 0) {
                console.log("Hooking " + match.name);
                Interceptor.attach(match.address, {
                    onEnter: function(args) {
                        console.log(args[2]);
                        var param = ObjC.Object(args[2]);                       
                    }
                }); 
            }           
        },
        onComplete: function () {
            send({event: 'ready'});
        }
    });
```

Structure of the method that I hook

``` ObjectiveC
    public class func stringForKey(keyName: String) -> String? {
        let keychainData: NSData? = self.dataForKey(keyName)
        var stringValue: String?
        if let data = keychainData {
            stringValue = NSString(data: data, encoding: NSUTF8StringEncoding) as String?
        }

        return stringValue
    }
```

Output

```
Hooking _TZFC14Target_iPhone18Classname12stringForKeyfSSGSqSS_
Hooking _TWoZFC14Target_iPhone18ClassName12stringForKeyfSSGSqSS_
0x40000012
{ type: 'error',
  description: 'Error: access violation accessing 0x68080440',
  stack: 'Error: access violation accessing 0x68080440\n    at Runtime.ObjCObject [as Object] (gumjs-objc.js:414:46)\n    at [object Object].Interceptor.attach.onEnter (script1.js:50:33)',
  fileName: 'gumjs-objc.js',
  lineNumber: 414,
  columnNumber: 46 }
0x40000012
{ type: 'error',
  description: 'Error: access violation accessing 0x68080440',
  stack: 'Error: access violation accessing 0x68080440\n    at Runtime.ObjCObject [as Object] (gumjs-objc.js:414:46)\n    at [object Object].Interceptor.attach.onEnter (script1.js:50:33)',
  fileName: 'gumjs-objc.js',
  lineNumber: 414,
  columnNumber: 46 }
```

**Comment by oleavr** [comment]
Hi,

The issue here is that [ObjC.Object](https://github.com/frida/frida-objc) is used to access a Swift object. Also note that `Module.enumerateExports()` will give you both exported functions and variables, so you should check the `type` so you only try to hook code, not data.

Cheers!

**Comment by neeru-thakur** [comment]
How could we access the Swift Object?

**Comment by lucassimao** [comment]
I'm having this same error acessing any method on android module, arm
