### ISSUE TITLE
Frida gadget crashes (frida_gadget_memory_range: assertion failed)

### ISSUE THREAD

**Issue by TheDauntless** [frida/frida-core#77]
Hi,

Environment:
**iOS:** 9.0.2
**iOS frida-server:** 7.1.12
**Gadget:** http://build.frida.re/frida/ios/lib/ (May 19th)
**OS X:** 7.1.12

I'm launching the application as follows:

```
IPAD:~ root# FRIDA_GADGET_SCRIPT=/var/root/disable.js FRIDA_GADGET_ENV=development     DYLD_INSERT_LIBRARIES=/var/root/gadget.dylib     /var/mobile/Containers/Bundle/Application/IDENTIFIER/APP.app/APP
```

However, it immediately gives this error:

```
2016-05-23 11:30:01.365 APP[692:8209] Frida: frida-   core/lib/gadget/gadget.c:6343:frida_gadget_memory_range: assertion failed: (result != null)
```

I can't find a frida_gadget_memory_range method in any of the source files, so I have no idea which code is triggering this.

**Comment by oleavr** [comment]
Hi,

You'll have to rename the dylib to `FridaGadget.dylib`, or more precisely, a name that contains either `FridaGadget` or `frida-gadget`, to satisfy [this](https://github.com/frida/frida-core/blob/f10cb3f5240b0cf100fb085547cb015a9b3e8943/lib/gadget/gadget.vala#L677). Note that the reason you didn't find the code from the C function name is that the code is written in Vala, which compiles to C – i.e. the namespace/class/function gets mangled into a combined name in all lower-case with underscores between.

Cheers!

**Comment by TheDauntless** [comment]
Hi Oleavr,

Thanks for your swift response. This does indeed fix the error that I received earlier. Maybe a better failure message would be nice.

I'm still getting "Abort trap: 6", but that most probably has a different cause..

**Comment by oleavr** [comment]
Glad to hear! Yeah it would be great to replace that assertion with an error followed by an error message. PR would be most appreciated :)
