### ISSUE TITLE
frida-server for Android x86 Emulator. possible?

### ISSUE THREAD

**Issue by Semyazz** [frida/frida-core#8]
How can I prepare frida-server for Android x86 (virtualbox/Genymotion based)?

**Comment by oleavr** [comment]
I take it you didn't find time to start on this, so I will give it a try. Just finished updating the build system, and currently building a new SDK for Android/x86. Stay tuned. :)

**Comment by oleavr** [comment]
There; Android/x86 is now supported in latest git. This will be part of the next Frida release, to be released soon.

**Comment by dequis** [comment]
:heart:

**Comment by oleavr** [comment]
:smile:

By the way, it looks like the Dalvik integration doesn't work. I'm afraid I'll have to wrap up this release now, as the weekend is about to end, so let's aim to fix that in the release after this one.

**Comment by mehdihz** [comment]
Is it now possible to use x86 version of frida? If yes, how can I compile to use it?

**Comment by oleavr** [comment]
Only the `arm` version is known to be working correctly, haven't had time to look at the Android `x86` port sadly. Feel like taking a stab at it?

**Comment by Manouchehri** [comment]
@oleavr Not sure if you've seen it yet or not, but Google now ships a x86 image in their emulator. It works miles better than trying to emulate an entire architecture. 

Would it be possible to host the x86 binary on build.frida.re?

**Comment by oleavr** [comment]
@Manouchehri Cool! It used to be on build.frida.re but I removed it after getting bug reports that I didn't have the bandwidth to handle. I can add it back but I could need some help testing it.

**Comment by Manouchehri** [comment]
I'd be happy to test. Feel free to upload it somewhere else if that's
easier.

**Comment by oleavr** [comment]
Awesome! Two freshly built binaries:
http://build.frida.re/frida-snapshot/android/i386/bin/frida-server
http://build.frida.re/frida-snapshot/android/x86_64/bin/frida-server

Note that I haven't tested them, so beware of dragons. :)

**Comment by Manouchehri** [comment]
Nice, thanks! I'll let you know how it goes. Want me to create a new issue
tracker or use this one?

**Comment by oleavr** [comment]
@Manouchehri Feel free to file issues either here in frida-core (for injection issues) or [frida-gum](https://github.com/frida/frida-gum) for instrumentation issues and Dalvik integration bugs, or [frida](https://github.com/frida/frida) for anything you're uncertain about.

**Comment by devinvisible** [comment]
I'm not sure if this is an issue with frida-core or elsewhere but I'm attempting to run:

frida-trace -U -i send com.supercell.clashofclans

and it says "Resolving functions..." but crashes my app. I'm running http://build.frida.re/frida-snapshot/android/i386/bin/frida-server on my Genymotion - Google Nexus 7 5.1.0 API 22 emuator (which seems to work just fine). Running frida-ps -U works and shows the target app without troubles.

How can I help you debug this further?

**Comment by clviper** [comment]
I have the same issue that devinvisible . When I run frida-trace -R process and in the fase of Instrumenting functions... the target proccess crashes in the device and I get a connection closed. I am  running the server on a Genymotion Google Nexus 4, API 17 and the client on linux.
