### ISSUE TITLE
Incompatible library version

### ISSUE THREAD

**Issue by KevinIsSun** [frida/frida-core#82]
When I inject FridaGarget.dylib into my execuate file, package it and install it to device, launch failed. The prompt was "Reason: Incompatible library version: execuate file requires version 1.0.0 or later, but FridaGadget.dylib provides version 0.0.0". I was really confused by this prompt. How can I fix it. Should I need to change the version of FridaGarget.dylib source code and recomplie it?Thanks for ur help!

**Comment by oleavr** [comment]
Which tool are you using to modify the Mach-O so it loads FridaGadget.dylib? Sounds like it might be hard-coding the version to `1.0.0` instead of detecting it from the input.

**Comment by KevinIsSun** [comment]
I use yololib. Sorry, I didn't check my email and found it just now.

**Comment by KevinIsSun** [comment]
thanks for ur opinion, I change a inject tool and it was fixed.

**Comment by oleavr** [comment]
Glad to hear!
