### ISSUE TITLE
Cyanogenmod restarts on calling frida.get_usb_device().spawn() ?

### ISSUE THREAD

**Issue by c4242** [frida/frida-core#86]
Starting com.android.chrome or org.mozilla.firefox results in simply that the Cyanogenmod GUI frontend restarts as if the device rebooted. Processes such as frida-server continue to run, however.

I have frida-server running in an adb shell.

I'm starting it on the client side with this simple statement:

pid = frida.get_usb_device().spawn([process])

Where process = "org.mozilla.firefox" or "com.android.chrome".

There is no other code in the .py program, this call blocks and eventually receives:

File "/usr/lib64/python2.7/site-packages/frida/core.py", line 84, in spawn return self._impl.spawn(argv)
frida.TimedOutError: unexpectedly timed out while waiting for app to launch

If I give it a bad name on purpose, frida-server reports "{"type":"error","description":"Error: Unable to find application with identifier ...", however, then it eventually also "reboots".

Frida-server version 7.3.1 (32-bit).
Frida on the client: version 7.3.1 (also tried 7.3.6, same result).
The host/client system is Gentoo.

getenforce on Android shows Permissive.

cm-11-20160815-NIGHTLY, Android version 4.4.4, kernel 3.0.64-CM-g2c43a00.

I attempted to strace frida-server on the Android device, but I couldn't see anything noteworthy. frida-server never terminates, even when the Android device "reboots".

Forgive me if this is something trivial that I'm simply overlooking. I tried searching for similar issues.

**Comment by oleavr** [comment]
Hi,

Thanks for reporting. I've heard of this issue, but haven't been lucky enough to have a device where it is reproducible. I suspect what happens here is that we crash Zygote. We basically [inject](https://github.com/frida/frida-core/blob/84192e25d5b7bb1396045a13afd10121ae3c849e/src/linux/linux-host-session.vala#L349) frida-loader-{32,64}.so into it, and then ask robo-agent.js to start the activity. The error you saw gets thrown [here](https://github.com/frida/frida-core/blob/84192e25d5b7bb1396045a13afd10121ae3c849e/src/linux/robo-agent.js#L42).

Let me know if you'd be interested in building Frida yourself to help debug this further. Basically `make server-android FRIDA_STRIP=no` to build a frida-server with debug symbols, and then attaching gdb to Zygote to figure out where it's crashing.

Cheers!

**Comment by c4242** [comment]
Thanks, I'm working on it.

zygote doesn't seem to like being attached to. The Android device "reboots" when I connect with gdb.

Gentoo:

(gdb) target remote 192.168.1.127:5039
Remote debugging using 192.168.1.127:5039
0x4014f860 in ?? ()
=> 0x4014f860:  00 00 00 ef     svc     0x00000000
(gdb) c
Continuing.

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb)

Android:

gdbserver :5039 --attach 31897                                                                                          
Attached; pid = 31897
Listening on port 5039
Remote debugging from host 192.168.1.136

Child terminated with signal = 0x9 (SIGKILL)
GDBserver exiting


PID 5039 is:

ps |grep -i zygote                                                                                                      
root      29843 1     502804 43332 ffffffff 401e5864 S zygote

**Comment by c4242** [comment]
Got it to cooperate simply by retrying (?). I will post when I have something.

**Comment by c4242** [comment]
Since it (gdb on zygote) decided to work now, I need the same version of Frida locally as I have on the Android device:

frida.ProtocolError: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use

However, when trying to do make python-64 (I'm assuming this is correct?), I get:

```
../../../../frida-core/src/linux/linux-host-session.c:16:31: fatal error: frida-data-loader.h: No such file or directory
 #include <frida-data-loader.h>
```

Copied that like so:

cp build/tmp-android-arm/frida-core/src/frida-data-loader.h frida-core/lib/agent/

Then:

```
../../../../frida-core/src/linux/linux-host-session.c:18:32: fatal error: frida-data-android.h: No such file or directory
#include <frida-data-android.h>
```

cp build/tmp-android-arm/frida-core/src/frida-data-android.h frida-core/lib/agent

I now get:

```
frida/build/frida-linux-x86_64/lib/libfrida-core-1.0.a(libfrida_core_la-linux-host-session.o): In function `frida_robo_launcher_construct':
frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/linux-host-session.c:4796: undefined reference to `frida_data_loader_get_frida_loader_32_so_blob'
frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/linux-host-session.c:4798: undefined reference to `frida_data_loader_get_frida_loader_64_so_blob'
frida/build/frida-linux-x86_64/lib/libfrida-core-1.0.a(libfrida_core_la-linux-host-session.o): In function `frida_robo_agent_construct':
frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/linux-host-session.c:7569: undefined reference to `frida_data_android_get_robo_agent_js_blob'
frida/build/frida-linux-x86_64/lib/libfrida-core-1.0.a(libfrida_core_la-frida-helper-process.o): In function `frida_resource_store_construct':
frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/frida-helper-process.c:3948: undefined reference to `setfilecon'
frida/build/frida-linux-x86_64/lib/libfrida-core-1.0.a(libfrida_core_la-linjector.o): In function `frida_agent_resource_get_path_template':
frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/linjector.c:1031: undefined reference to `setfilecon'
frida/build/tmp-linux-x86_64/frida-core/src/../../../../frida-core/src/linux/linjector.c:1116: undefined reference to `setfilecon'
```

I'm assuming I'm doing something wrong?

**Comment by oleavr** [comment]
@c4242 Thanks for looking into this! Our current build system has a flaw where some assets are only generated once, so you need to be careful if you use the same working tree to build for two different OSes. You can do `make clean` between them, or clone the `frida` repo twice. If you start from a clean tree, does `make python-64` still fail like above?

**Comment by c4242** [comment]
Thanks for fast assistance!

When I try to build from a clean tree I got this:

```
make[1]: *** No rule to make target 'build/frida-linux-i386/lib/pkgconfig/frida-gum-1.0.pc', needed by 'build/tmp-linux-i386/frida-core/Makefile'.  Stop.
make[1]: Leaving directory '/home/cwo/temp_git2/frida'
Makefile:2: recipe for target 'python-64' failed
make: *** [python-64] Error 2
```

I decided to try the command I found in this issue: https://github.com/frida/frida/issues/33

make clean
make -f Makefile.sdk.mk FRIDA_HOST=linux-x86_64

This seemed to proceed fine. I then reattempted the python-64 build: 

```
rm -rf build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida
mkdir -p build/frida_stripped-linux-x86_64/lib/python2.7/site-packages
cp -a build/frida-linux-x86_64/lib/python2.7/site-packages/frida build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida
cp: cannot stat 'build/frida-linux-x86_64/lib/python2.7/site-packages/frida': No such file or directory
Makefile.linux.mk:462: recipe for target 'build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida' failed
make[1]: *** [build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida] Error 1
make[1]: Leaving directory '/home/cwo/temp_git2/frida'
Makefile:2: recipe for target 'python-64' failed
make: *** [python-64] Error 2
```

Different error but no success.

**Comment by oleavr** [comment]
@c4242 Ah yes, sorry about that. That first error is actually a build system bug that happens with a clean tree on Linux. Just run the command again and it should be able to resume. (It may fail with "npm: command not found" after that, so if it does make sure you get the latest Node.js 6.x and have it on your PATH.)

**Comment by c4242** [comment]
I removed everything and did a fresh clone, then make python-64 ; make python-64.

The first build failed as before with the expected: make[1]: *** No rule to make target 'build/frida-linux-i386/lib/pkgconfig/frida-gum-1.0.pc', needed by 'build/tmp-linux-i386/frida-core/Makefile'.  Stop.

The second failed with the following:

```
rm -rf build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida
mkdir -p build/frida_stripped-linux-x86_64/lib/python2.7/site-packages
cp -a build/frida-linux-x86_64/lib/python2.7/site-packages/frida build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida
cp: cannot stat 'build/frida-linux-x86_64/lib/python2.7/site-packages/frida': No such file or directory
Makefile.linux.mk:462: recipe for target 'build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida' failed
make[1]: *** [build/frida_stripped-linux-x86_64/lib/python2.7/site-packages/frida] Error 1
make[1]: Leaving directory '/home/cwo/temp_git/frida'
Makefile:2: recipe for target 'python-64' failed
make: *** [python-64] Error 2
```

I'm not sure if Node.js is related to this, but I only had 4.4.6 (the stable build used in Gentoo). I upgraded this to 6.7.0 and retried. But the result is the same.

**Comment by oleavr** [comment]
@c4242 It looks like frida-python didn't install to the expected location. Could you paste the output from when frida-python was being built and installed?

**Comment by c4242** [comment]
I have the whole build log wgetpasted here: https://paste.pound-python.org/show/2I9EgJNlOgUN7hjnE7Sc/

I tried looking at it but unfortunately it is not clear to me what the problem is.

**Comment by c4242** [comment]
Is this relevant?

```
 /bin/mkdir -p '/home/expc/temp_git/frida/build/frida-linux-x86_64/lib64/python2.7/site-packages/frida'
 /usr/bin/install -p -m 644 ../../../../../frida-python/src/frida/__init__.py ../../../../../frida-python/src/frida/core.py ../../../../../frida-python/src/frida/application.py ../../../../../frida-python/src/frida/ps.py ../../../../../frida-python/src/frida/discoverer.py ../../../../../frida-python/src/frida/tracer.py ../../../../../frida-python/src/frida/repl.py '/home/expc/temp_git/frida/build/frida-linux-x86_64/lib64/python2.7/site-packages/frida'
```

**Comment by c4242** [comment]
Seems like this was enough:

`~/temp_git/frida/build/frida-linux-x86_64/lib $ ln -s ../lib64/python2.7/ ./`

**Comment by c4242** [comment]
Sorry for the delays. Finally I have a setup I think is working, but I get this error:

```
  File "/usr/lib64/python2.7/site-packages/frida/core.py", line 84, in spawn
    return self._impl.spawn(argv)
frida.PermissionDeniedError: unable to access process with pid 14467 due to system restrictions; try `sudo sysctl kernel.yama.ptrace_scope=0`, or run Frida as root

```

However, I am running Frida as root. On both the Android device and on the Gentoo system.

I get that when I start Frida on the Gentoo host. This only happens when I'm attached to zygote via gdbserver on the android device (I'm also connected to gdbserver from the Gentoo host, and I have continued the execution, zygote is running). If I quit gdbserver, I can immediately run the frida script again as normal (and the device restarts as before).

Any advices?

**Comment by oleavr** [comment]
(Assuming this is fixed.)
