### ISSUE TITLE
Failed to attach: the connection is closed

### ISSUE THREAD

**Issue by ddaddy** [frida/frida-core#87]
I am trying to use `frida-trace` on an iOS 9.3.3 iPod Touch and keep getting the error `Failed to attach: the connection is closed` when running the command `frida-trace -U -n SpringBoard`.

Running `frida-ps -U` works fine.

It works fine on an iOS 8 device.

**Comment by oleavr** [comment]
Hi,

Which version of Frida is this? I'm afraid I don't have any 9.x devices I can use for testing anymore, so could use some help debugging this. :-)

Thanks!

**Comment by piaoapiao** [comment]
8.1.1

**Comment by ddaddy** [comment]
I'm using `8.1.0` for OSX and `8.0.3` on iOS.
Let me know what you need for me to help.

**Comment by ddaddy** [comment]
I am still struggling to get frida to connect on iOS 9 using frida `8.1.10`. Anything I can do to help fix this?

**Comment by oleavr** [comment]
@ddaddy How did you install Frida? It's important that `frida-server` is started through launchd, with the exact [configuration](https://github.com/frida/frida-core/blob/ad5635b5c1ff9ea3a3e5f052010f0fe0c2582e21/tools/package-server.sh#L32-L65) that our iOS .deb uses.

**Comment by ddaddy** [comment]
I used your cydia distro to install.

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
