### ISSUE TITLE
frida-server for Android x86 Emulator

### ISSUE THREAD

**Issue by DmitriyChernov** [frida/frida-core#88]
Hello, thats my problem:
i'm trying to set-up frida-server on my Android x86 emulator. I've got prebuids of frida-server from here: http://build.frida.re/frida-snapshot/android/ and pushed it to virtual device. Now i trying to connect them and getting following output:
"Failed to enumerate processes: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use".
My version of frida, running in my ubuntu-os is up-to-date. Version of frida-server snapshots: 6.0.12.1.g6865ae8.
So that's my question: are those snapshots actual today or i should build them by myself to connect to frida-server?

**Comment by oleavr** [comment]
Hi,

I'm afraid Android x86 support is experimental, so we no longer generate binaries for it (and I should have removed the old snapshots to avoid confusion). If you're interested in hacking on Frida I would encourage you to build it locally and submit PRs for any issues you find, but if you just want to use Frida I would recommend using the latest binary for ARM (from https://github.com/frida/frida/releases) on a 4.4 emulator image.

Cheers!

**Comment by DmitriyChernov** [comment]
I have problems with performance on ARM emulator, so i would try to build it myself, thank you.

**Comment by haomnguyen** [comment]
Is there any good news regarding x86 Android? Emulators are all x86.

**Comment by oleavr** [comment]
@haomnguyen It's fully supported.

**Comment by haomnguyen** [comment]
Hi Ole,

Thanks for replying. Let me try. It's an amazing framework from what I read.

Which part of the framework handles library injection for Android x86?

Best Regards,
Hao Nguyen

On Jun 4, 2017, at 1:52 PM, Ole André Vadla Ravnås <notifications@github.com<mailto:notifications@github.com>> wrote:


@haomnguyen<https://github.com/haomnguyen> It's fully supported.

**Comment by oleavr** [comment]
@haomnguyen Thanks! You can find the code here:
https://github.com/frida/frida-core/blob/master/src/linux/frida-helper-service-glue.c

Speaking of that, @karltk and me gave a talk walking through the library injection part for Android/Linux:
https://www.youtube.com/watch?v=uc1mbN9EJKQ
