### ISSUE TITLE
Frida-server not running properly? 

### ISSUE THREAD

**Issue by illegalPointer** [frida/frida-core#89]
Hello, 

I´m having some issues trying to run frida on my mobile phone.
The mobile is a BQ Aquaris M5, with Android 5.0.1. Frida version 8.7.1

$adb shell
shell@Aquaris_M5:/ $ su
root@Aquaris_M5:/ # cd /data/local/tmp
root@Aquaris_M5:/data/local/tmp # ./frida-server
WARNING: linker: ./frida-server: unused DT entry: type 0x6ffffffe arg 0x441dc
WARNING: linker: ./frida-server: unused DT entry: type 0x6fffffff arg 0x2

I received those warnings and when I execute frida-ps -U i only got "Waiting for USB device to appear..."

Thanks!
Pablo.

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x. (Those linker warnings are harmless btw.)
