### ISSUE TITLE
Frida on Android relies on hardcoded SuperSU to elevate frida-helper

### ISSUE THREAD

**Issue by 0xABD** [frida/frida-core#90]
Frida on Android e.g. as if in ```frida-core/src/linux/frida-helper-process.vala``` relies on hardcoded name of ```su``` binary and SuperSU control socket ```eu.chainfire.supersu```. 
It would be beneficial to make such assumptions in Frida binaries configurable, especially for stealth-oriented use cases (i.e. when all non-standard binaries are patched/renamed/moved to avoid detection) on locked-down devices where elevation must be performed this way only due to SELinux configuration, etc.

**Comment by oleavr** [comment]
PR welcome!
