### ISSUE TITLE
Android Nexus 5 (Cyanogen 5.1.1) - Failed to enumerate applications: the connection is closed

### ISSUE THREAD

**Issue by clviper** [frida/frida-core#98]
Hi there.

I'm trying to use the version 8.2.3 in Windows 7 x64. The Android device has the same server version.

When I start the server in Android I get the following warnings:

_WARNING: linker: ./frida-server: unused DT entry: type 0x6ffffffe arg 0x47584
WARNING: linker: ./frida-server: unused DT entry: type 0x6fffffff arg 0x2_

When I try to use _frida-ps -Ua_ I get the following error:

_Failed to enumerate applications: the connection is closed_

In the server in the device I receive the following warnings:

_WARNING: linker: /data/local/tmp/re.frida.server/frida-helper-32: unused DT entry: type 0x6ffffffe arg 0x4599c
WARNING: linker: /data/local/tmp/re.frida.server/frida-helper-32: unused DT entry: type 0x6fffffff arg 0x2_

I have the SELinux set to Permissive.

Any ideas?

Thank you.

**Comment by oleavr** [comment]
Sorry for the delay! Assuming this is fixed in latest Frida 9.x. Please let me know if this is not the case.
