### ISSUE TITLE
frida-server not working on Android 7.x ARM emulator

### ISSUE THREAD

**Issue by mirkobrandner** [frida/frida-core#99]
Due to a lack of overview which version of Android is actually supported, I file this issue:

./frida-server-8.2.2-android-arm                   (or 8.2.3)                                                           
  libsepol.avtab_read_item: more than one specifier
  libsepol.avtab_read: failed on entry 120 of 6489
  Unable to load SELinux policy from the kernel: unsupported policy database format

It is not stopping but I cannot connect from client, e.g.:
frida-ps -U
  Failed to enumerate processes: unable to connect to remote frida-server: closed

Maybe this is not supported at all, then I would like to ask the community to tell me where we could gather this info or experience.

**Comment by mattbrun** [comment]
I've encountered the same output errors with Android 7.1.1 (CyanogenMod 14.1-20161225) and frida-server 8.2.5 for ARM.
I do have root on the devices, enabled for both `adb` and apps.
I'm using a Motorola G 2^ gen. with processor ARMv7 Processor rev 3 (v7l) - Qualcomm MSM8226 - which has a 32 bit architecture.
```bash
$ adb shell
titan:/ # /data/local/tmp/frida-server &                                                                             
[1] 10595
titan:/ # libsepol.avtab_read_item: more than one specifier
libsepol.avtab_read: failed on entry 218 of 14129
Unable to load SELinux policy from the kernel: unsupported policy database format

titan:/ # 
```
The same output is given launching `frida-server` through `adb shell`.

As @mirkobrandner sad the server is starting anyway, but contrary to @mirkobrandner I can connect to it, because `frida-ps -U` works well.
```bash
Waiting for USB device to appear...
  PID  Name
-----  --------------------------------------------------
30591  adbd
 2264  adsprpcd
 5575  android.process.media
 2286  audiod
 2275  audioserver
 2259  batt_health
...
```
The problem is that I can't attach to a running process.
```bash
$ frida-trace -U -i open com.android.chrome
Waiting for USB device to appear...
Failed to attach: unexpectedly timed out while waiting for FIFO to establish
```
After this `frida-trace` exit and the app crashes.
This happens for all the apps I tried out.

Thanks for the help and the good work.

**Comment by alkman** [comment]
I'm seeing the same problem with 9.0.13. Didn't see this ticket and opened ticket #218 under frida/frida. It looks like they could be combined.

**Comment by codehz** [comment]
In the real machine can not work properly....
```
OnePlus3T:/ $ su -c /data/local/tmp/fri*
su -c /data/local/tmp/fri*
libsepol.avtab_read_item: more than one specifier
libsepol.avtab_read: failed on entry 5810 of 96207
Unable to load SELinux policy from the kernel: unsupported policy database format
```
If I dont use `su`
```
/data/local/tmp/fri*
libsepol.avtab_read_item: more than one specifier
libsepol.avtab_read: failed on entry 5810 of 96207
Unable to load SELinux policy from the kernel: unsupported policy database format
Aborted (core dumped)
```
But both cases can not be connected to.
```
Waiting for USB device to appear...
Failed to enumerate processes: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use
```
PS: SELinux has been disabled..

**Comment by max01203** [comment]
Hi,
I think that you have to ensure that you have the latest version of frida using pip and using the latest frida server in the github.
To upgrade frida using pip run:
sudo pip install frida --upgrade

To get the latest version of frida server check the releases in https://github.com/frida/frida

Thanks

**Comment by Rick11929** [comment]
Hi , 
i still facing this issue in the latest version 
error log : Failed to attach: unexpectedly timed out while waiting for FIFO to establish

**Comment by stevielavern** [comment]
Also having the issue on frida 11.0.2 on linux ARM. Is there a way to troubleshoot the issue?

**Comment by oleavr** [comment]
> Also having the issue on frida 11.0.2 on linux ARM.
Please don't report issues with outdated versions of Frida. Always test on the latest.

**Comment by stevielavern** [comment]
Sorry @oleavr that was a typo, I really meant 11.0.12, which is the latest version that I recompiled. The issue appears on linux ARM but only on some processes though.

**Comment by oleavr** [comment]
Ah ok! Let's continue our discussion [here](https://github.com/frida/frida-website/issues/31#issuecomment-400243936).

**Comment by Jahanzaeb** [comment]
@oleavr we are facing same issue as mentioned above we are runing frida server as root on [Samsung galaxy A710FD) but facing same error :
"Unable to load SELinux policy from the kernel: Failed to open file ΓÇ£/sys/fs/selinux/policyΓÇ¥: Permission denied"
Please guide me how I can fix this issue?
